### ISSUE TITLE
Tests fail on s390x system

### ISSUE THREAD

**Issue by jirutka** [WebAssembly/binaryen#1012]
```
executing:  bin/wasm-merge test/merge/dylib.wasm test/merge/dylib.wasm.toMerge -o a.wast -S --verbose --finalize-memory-base=1024 --finalize-table-base=8incorrect output, diff:

--- expected
+++ actual
@@ -3,7 +3,7 @@
  (import "env" "memory" (memory $0 1))
  (table 2 2 anyfunc)
  (elem (i32.const 0) $__wasm_nullptr $__exit)
- (data (i32.const 16) "\d2\04\00\00\00\00\00\00)\t\00\00")
+ (data (i32.const 16) "\00\00\04\d2\00\00\00\00\00\00\t)")
  (export "__exit" (func $__exit))
  (export "__needs_exit" (func $__needs_exit))
  (export "dynCall_v" (func $dynCall_v))


executing:  bin/wasm-merge test/merge/dylib.wasm test/merge/dylib.wasm.toMerge -o a.wast -S --verbose --finalize-memory-base=1024 --finalize-table-base=8 -O

[ checking wasm-shell spec testcases... ]


[ checking .s testcases... ]

executing:  bin/s2wasm /home/buildozer/aports/community/binaryen/src/binaryen-1.37.12/test/dot_s/basics.s --import-memory
.. alias.s
executing:  bin/s2wasm /home/buildozer/aports/community/binaryen/src/binaryen-1.37.12/test/dot_s/alias.s --emscripten-glue
Traceback (most recent call last):
  File "check.py", line 344, in <module>
    s2wasm.test_s2wasm()
  File "/home/buildozer/aports/community/binaryen/src/binaryen-1.37.12/scripts/test/s2wasm.py", line 57, in test_s2wasm
    fail(actual, expected)
  File "/home/buildozer/aports/community/binaryen/src/binaryen-1.37.12/scripts/test/shared.py", line 324, in fail
    fail_with_error("incorrect output, diff:\n\n%s" % diff_str)
  File "/home/buildozer/aports/community/binaryen/src/binaryen-1.37.12/scripts/test/shared.py", line 312, in fail_with_error
    raise Exception(msg)
Exception: incorrect output, diff:

--- expected
+++ actual
@@ -3,7 +3,7 @@
  (import "env" "memory" (memory $0 1))
  (table 2 2 anyfunc)
  (elem (i32.const 0) $__wasm_nullptr $__exit)
- (data (i32.const 16) "\d2\04\00\00\00\00\00\00)\t\00\00")
+ (data (i32.const 16) "\00\00\04\d2\00\00\00\00\00\00\t)")
  (export "__exit" (func $__exit))
  (export "__needs_exit" (func $__needs_exit))
  (export "dynCall_v" (func $dynCall_v))
```

Complete build log: [binaryen-1.37.12-r0.log.txt](https://github.com/WebAssembly/binaryen/files/998527/binaryen-1.37.12-r0.log.txt)

**Comment by jfbastien** [comment]
Looks like endianness bug.

**Comment by kripken** [comment]
Closing as duplicate of #2983 (which is newer, but has more discussion)
