### ISSUE TITLE
asm2wasm fails without descriptive error

### ISSUE THREAD

**Issue by nazar-pc** [WebAssembly/binaryen#1129]
I'm trying to compile a quite large library https://github.com/rweather/noise-c

I'm exporting necessary functions, but stuck on 34 explicitly listed functions. As soon as 35th is added, compilation fails without any descriptive error, while with any 34 functions it works fine. It feels like there is a limit of 34 functions or some other limit on which `asm2wasm` fails with exit code `-6`.

emcc is executed with this command:
```
EMMAKEN_CFLAGS='-imacros macros.h -I vendor/include -I vendor/src -I vendor/src/crypto/goldilocks/src/include -I vendor/src/crypto/goldilocks/src/p448 -I vendor/src/crypto/goldilocks/src/p448/arch_32' emcc noise-c.c vendor/src/protocol/cipherstate.c vendor/src/protocol/dhstate.c vendor/src/protocol/errors.c vendor/src/protocol/handshakestate.c vendor/src/protocol/hashstate.c vendor/src/protocol/internal.c vendor/src/protocol/names.c vendor/src/protocol/patterns.c vendor/src/protocol/randstate.c vendor/src/protocol/signstate.c vendor/src/protocol/symmetricstate.c vendor/src/protocol/util.c vendor/src/protocol/../backend/ref/dh-curve448.c vendor/src/protocol/../backend/ref/dh-newhope.c vendor/src/protocol/../backend/ref/hash-blake2s.c vendor/src/protocol/../crypto/blake2/blake2s.c vendor/src/protocol/../crypto/curve448/curve448.c vendor/src/protocol/../crypto/goldilocks/src/p448/arch_32/p448.c vendor/src/protocol/../crypto/newhope/batcher.c vendor/src/protocol/../crypto/newhope/error_correction.c vendor/src/protocol/../crypto/newhope/fips202.c vendor/src/protocol/../crypto/newhope/newhope.c vendor/src/protocol/../crypto/newhope/ntt.c vendor/src/protocol/../crypto/newhope/poly.c vendor/src/protocol/../crypto/newhope/precomp.c vendor/src/protocol/../crypto/newhope/reduce.c vendor/src/protocol/../backend/ref/cipher-aesgcm.c vendor/src/protocol/rand_os.c vendor/src/protocol/../backend/ref/cipher-aesgcm.c vendor/src/protocol/../backend/ref/cipher-chachapoly.c vendor/src/protocol/../backend/ref/dh-curve25519.c vendor/src/protocol/../backend/ref/hash-blake2b.c vendor/src/protocol/../backend/ref/hash-sha256.c vendor/src/protocol/../backend/ref/hash-sha512.c vendor/src/protocol/../backend/ref/sign-ed25519.c vendor/src/protocol/../crypto/aes/rijndael-alg-fst.c vendor/src/protocol/../crypto/blake2/blake2b.c vendor/src/protocol/../crypto/chacha/chacha.c vendor/src/protocol/../crypto/donna/poly1305-donna.c vendor/src/protocol/../crypto/ghash/ghash.c vendor/src/protocol/../crypto/newhope/crypto_stream_chacha20.c vendor/src/protocol/../crypto/sha2/sha256.c vendor/src/protocol/../crypto/sha2/sha512.c vendor/src/protocol/../crypto/ed25519/ed25519.c -o noise-c.js -s MODULARIZE=1 -s EXPORTED_FUNCTIONS='["_malloc","_free","_noise_cipherstate_struct_size","_noise_cipherstate_decrypt","_noise_cipherstate_decrypt_with_ad","_noise_cipherstate_encrypt","_noise_cipherstate_encrypt_with_ad","_noise_cipherstate_free","_noise_cipherstate_get_cipher_id","_noise_cipherstate_get_key_length","_noise_cipherstate_get_mac_length","_noise_cipherstate_get_max_key_length","_noise_cipherstate_get_max_mac_length","_noise_cipherstate_has_key","_noise_cipherstate_init_key","_noise_cipherstate_new_by_id","_noise_cipherstate_new_by_name","_noise_cipherstate_set_nonce","_noise_handshakestate_struct_size","_noise_handshakestate_fallback","_noise_handshakestate_fallback_to","_noise_handshakestate_free","_noise_handshakestate_get_action","_noise_handshakestate_get_fixed_ephemeral_dh","_noise_symmetricstate_struct_size","_noise_symmetricstate_decrypt_and_hash","_noise_symmetricstate_encrypt_and_hash","_noise_symmetricstate_free","_noise_symmetricstate_get_mac_length","_noise_symmetricstate_get_protocol_id","_noise_symmetricstate_mix_hash","_noise_symmetricstate_mix_key","_noise_symmetricstate_new_by_id","_noise_symmetricstate_new_by_name","_noise_symmetricstate_split"]' -s WASM=1 -O2 --closure 1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=[] -s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]
```

The result is:
```
Traceback (most recent call last):
  File "/home/nazar-pc/bin/emcc", line 13, in <module>
    emcc.run()
  File "/media/Data/emsdk-portable/emscripten/1.37.18/emcc.py", line 1785, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/media/Data/emsdk-portable/emscripten/1.37.18/emcc.py", line 2256, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/media/Data/emsdk-portable/clang/e1.37.18_64bit/binaryen/bin/asm2wasm', 'noise-c.temp.asm.js', '--total-memory=16777216', '--emit-potential-traps', '-O2', '--mem-init=noise-c.js.mem', '--mem-base=1024', '--wasm-only', '-o', 'noise-c.wasm']' returned non-zero exit status -6
```

[emcc.log.txt](https://github.com/WebAssembly/binaryen/files/1213649/emcc.log.txt)

**Comment by kripken** [comment]
It's possible it's running out of memory on your machine. I'd look at a memory monitor as it runs, see if something odd happens.

If that's not it, please try to make a standalone testcase showing the issue (as small as possible, single input file, etc.).

**Comment by nazar-pc** [comment]
I have 32GiB of RAM and compilation doesn't consume any significant amount of it (less than 1% anyway).
Also standalone testcase wouldn't be small, since it compiles with 34 exported functions and doesn't with 35. Looks like it doesn't matter which exact functions are exported, I can pick another 35 functions and it still fails.

Do you have any ideas what can I do to debug this further, other than `EMCC_DEBUG=1` and `-v` which do not print anything useful? As the last resort I'll just upload it as is, but there is a lot of code there.

The only file which is present after failure is `noise-c.js.mem`, no js or wasm files.

**Comment by nazar-pc** [comment]
This is clearly asm2wasm issue, with `WASM=0` compilation finished fine, attaching artifacts (js and mem files).
[noise-c.wasm.zip](https://github.com/WebAssembly/binaryen/files/1214629/noise-c.wasm.zip)

**Comment by nazar-pc** [comment]
Intermediate files that cause asm2wasm to exit with SIGABRT:
[noise-c.wasm.zip](https://github.com/WebAssembly/binaryen/files/1214701/noise-c.wasm.zip)

```
nazar-pc@nazar-pc /w/g/noise-c.wasm> /media/Data/emsdk-portable/clang/e1.37.18_64bit/binaryen/bin/asm2wasm -d -g noise-c.temp.asm.js --total-memory=16777216 -O2 --mem-init=noise-c.js.mem --mem-base=1024 --wasm-only -o noise-c.wasm
Loading 'noise-c.temp.asm.js'...
parsing...
wasming...
asm2wasming func: stackAlloc
asm2wasming func: stackSave
asm2wasming func: stackRestore
asm2wasming func: establishStackSpace
asm2wasming func: setThrew
asm2wasming func: setTempRet0
asm2wasming func: getTempRet0
asm2wasming func: _noise_cipherstate_struct_size
asm2wasming func: _noise_handshakestate_struct_size
asm2wasming func: _noise_symmetricstate_struct_size
asm2wasming func: _noise_cipherstate_new_by_id
asm2wasming func: _noise_cipherstate_new_by_name
asm2wasming func: _noise_cipherstate_free
asm2wasming func: _noise_cipherstate_get_cipher_id
asm2wasming func: _noise_cipherstate_get_key_length
asm2wasming func: _noise_cipherstate_get_mac_length
asm2wasming func: _noise_cipherstate_init_key
asm2wasming func: _noise_cipherstate_has_key
asm2wasming func: _noise_cipherstate_encrypt_with_ad
asm2wasming func: _noise_cipherstate_decrypt_with_ad
asm2wasming func: _noise_cipherstate_encrypt
asm2wasming func: _noise_cipherstate_decrypt
asm2wasming func: _noise_cipherstate_set_nonce
asm2wasming func: _noise_cipherstate_get_max_key_length
asm2wasming func: _noise_cipherstate_get_max_mac_length
asm2wasming func: _noise_dhstate_new_by_id
asm2wasming func: _noise_dhstate_free
asm2wasming func: _noise_dhstate_has_keypair
asm2wasming func: _noise_dhstate_has_public_key
asm2wasming func: _noise_dhstate_generate_dependent_keypair
asm2wasming func: _noise_dhstate_clear_key
asm2wasming func: _noise_dhstate_set_public_key
asm2wasming func: _noise_dhstate_is_null_public_key
asm2wasming func: _noise_dhstate_calculate
asm2wasming func: _noise_dhstate_get_role
asm2wasming func: _noise_dhstate_set_role
asm2wasming func: _noise_handshakestate_new_by_id
asm2wasming func: _noise_handshakestate_new
asm2wasming func: _noise_handshakestate_free
asm2wasming func: _noise_handshakestate_new_by_name
asm2wasming func: _noise_handshakestate_get_role
asm2wasming func: _noise_handshakestate_get_protocol_id
asm2wasming func: _noise_handshakestate_get_local_keypair_dh
asm2wasming func: _noise_handshakestate_get_remote_public_key_dh
asm2wasming func: _noise_handshakestate_get_fixed_ephemeral_dh
asm2wasming func: _noise_handshakestate_get_fixed_hybrid_dh
asm2wasming func: _noise_handshakestate_needs_pre_shared_key
asm2wasming func: _noise_handshakestate_has_pre_shared_key
asm2wasming func: _noise_handshakestate_set_pre_shared_key
asm2wasming func: _noise_handshakestate_set_prologue
asm2wasming func: _noise_handshakestate_needs_local_keypair
asm2wasming func: _noise_handshakestate_has_local_keypair
asm2wasming func: _noise_handshakestate_needs_remote_public_key
asm2wasming func: _noise_handshakestate_has_remote_public_key
asm2wasming func: _noise_handshakestate_start
asm2wasming func: _noise_handshakestate_fallback
asm2wasming func: _noise_handshakestate_fallback_to
asm2wasming func: _noise_handshakestate_get_action
asm2wasming func: _noise_handshakestate_write_message
asm2wasming func: _noise_handshake_mix_dh
asm2wasming func: _noise_handshakestate_read_message
asm2wasming func: _noise_handshakestate_split
asm2wasming func: _noise_handshakestate_get_handshake_hash
asm2wasming func: _noise_hashstate_new_by_id
asm2wasming func: _noise_hashstate_free
asm2wasming func: _noise_hashstate_get_hash_length
asm2wasming func: _noise_hashstate_hash_one
asm2wasming func: _noise_hashstate_hash_two
asm2wasming func: _noise_hashstate_hkdf
asm2wasming func: _noise_hashstate_hmac
asm2wasming func: _noise_aesgcm_new
asm2wasming func: _noise_name_to_id
asm2wasming func: _noise_protocol_name_to_id
asm2wasming func: _noise_protocol_id_to_name
asm2wasming func: _noise_pattern_lookup
asm2wasming func: _noise_pattern_reverse_flags
asm2wasming func: _noise_symmetricstate_new_by_id
asm2wasming func: _noise_symmetricstate_new
asm2wasming func: _noise_symmetricstate_new_by_name
asm2wasming func: _noise_symmetricstate_free
asm2wasming func: _noise_symmetricstate_get_protocol_id
asm2wasming func: _noise_symmetricstate_mix_key
asm2wasming func: _noise_symmetricstate_mix_hash
asm2wasming func: _noise_symmetricstate_encrypt_and_hash
asm2wasming func: _noise_symmetricstate_decrypt_and_hash
asm2wasming func: _noise_symmetricstate_get_mac_length
asm2wasming func: _noise_symmetricstate_split
asm2wasming func: _noise_new_object
asm2wasming func: _noise_free
asm2wasming func: _noise_clean
asm2wasming func: _noise_is_equal
asm2wasming func: _noise_is_zero
asm2wasming func: _noise_curve448_new
asm2wasming func: _noise_curve448_generate_keypair
asm2wasming func: _noise_curve448_set_keypair
asm2wasming func: _noise_curve448_set_keypair_private
asm2wasming func: _noise_curve448_validate_public_key
asm2wasming func: _noise_curve448_copy
asm2wasming func: _noise_curve448_calculate
asm2wasming func: _noise_newhope_new
asm2wasming func: _noise_newhope_generate_keypair
asm2wasming func: _noise_newhope_set_keypair
asm2wasming func: _noise_newhope_set_keypair_private
asm2wasming func: _noise_newhope_validate_public_key
asm2wasming func: _noise_newhope_copy
asm2wasming func: _noise_newhope_calculate
asm2wasming func: _noise_newhope_change_role
asm2wasming func: _noise_blake2s_new
asm2wasming func: _noise_blake2s_reset
asm2wasming func: _noise_blake2s_update
asm2wasming func: _noise_blake2s_finalize
asm2wasming func: _BLAKE2s_reset
asm2wasming func: _BLAKE2s_update
asm2wasming func: _blake2s_transform
asm2wasming func: _BLAKE2s_finish
asm2wasming func: _curve448_eval
fish: “/media/Data/emsdk-portable/clan…” terminated by signal SIGABRT (Abort)
```

**Comment by nazar-pc** [comment]
Well, it is not limited by number of functions. Looks like the size of `noise-c.temp.asm.js` is causing things to fail. 412.6 KiB file works fine, 1.2-1.3 MiB file crashes.

What is the limit and how to change it?

**Comment by kripken** [comment]
Running this in a debug build in gdb, the crash is because it sees a SIMD type. SIMD is not supported in wasm yet.

We should have an error on this in emscripten, but maybe it's not working properly. Did you build with SIMD=1? That matters for what type of error detection should be used.

**Comment by nazar-pc** [comment]
I didn't specify `SIMD=1`, exact command used for compilation is in the first message and in log file.
Does SIMD depend on compilation options only or it may also be specified in source code somehow?
The source code I'm using is this: https://github.com/rweather/noise-c

**Comment by nazar-pc** [comment]
Looks like #855, but without descriptive error from asm2wasm this time.
When looking at clang options I'm wondering where `-vectorize-loops -vectorize-slp` come from. Is it because of emscripten-fastcomp-clang?

**Comment by nazar-pc** [comment]
There are also some files in the code base that explicitly use vectorization:
```c
#if defined(__SSE2__) && defined(__GNUC__) && __GNUC__ >= 4
#define USE_VECTOR_MATH 1
...
#else
#undef USE_VECTOR_MATH
#endif
```

**Comment by kripken** [comment]
Yeah, I think that's it - explicit vectorization leads to SIMD being enabled even without the option being specified. Looks like we're missing checks, I opened https://github.com/kripken/emscripten/pull/5462

**Comment by nazar-pc** [comment]
With mentioned PR I'm getting `SIMD is used, but not supported in WASM mode yet`, which is useful.
Is there a way to de-vectorize code or something like that?

**Comment by nazar-pc** [comment]
OK, solutions is not related to this project in general, so I'm closing issue, thanks for your help!

**Comment by nazar-pc** [comment]
In my case there are no `#define`: https://gist.github.com/nazar-pc/984c342f0dd7bc4e0ae383a47033d319
Now I'm looking for someone to convert it to SIMD-free and then will write a patch to be applied to sources before compilation.

It is interesting how old problems like lacking SIMD support come back with new tech like WebAssembly.

**Comment by kripken** [comment]
It might be worth looking for an LLVM pass that removes SIMD from IR. I haven't heard of one but it seems practical and maybe someone created it.
