### ISSUE TITLE
binaryen.js builds are broken with emscripten 1.37.18+

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1135]
It appears that a recent change to emscripten (somewhen between [7/24](https://travis-ci.org/dcodeIO/binaryen.js/builds/256999604#L3535) and [7/26](https://travis-ci.org/dcodeIO/binaryen.js/builds/257841963#L3537), possibly [9a18081](https://github.com/kripken/emscripten/commit/9a180811af501a0eb6ecb154656e0a828d23a952)) broke binaryen.js builds.

```js
var mod = new binaryen.Module();
mod.i32.const(0); // throws RangeError: Maximum call stack size exceeded
```

To be sure, I also tried to reproduce the issue locally, finding that 1.37.17 works, while compilation with 1.37.18+ results in the error above.

Full errors I've seen:
```
RangeError: Maximum call stack size exceeded
    at Array.qBa (binaryen.js:623:131579)
    at Object.Wxa [as dynCall_iii] (binaryen.js:623:122726)
    at invoke_iii (binaryen.js:600:19)
    at kn (binaryen.js:619:16987)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)

RangeError: Maximum call stack size exceeded
    at Object.Wxa [as dynCall_iii] (binaryen.js:623:122684)
    at invoke_iii (binaryen.js:600:19)
    at kn (binaryen.js:619:16987)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
    at kn (binaryen.js:619:17368)
```

**Comment by kripken** [comment]
Hmm, that seems very bad. First thing, can you use `git bisect` to find the specific changeset that caused this, or is `9a18081` that you mentioned the result of bisection?

**Comment by dcodeIO** [comment]
It seems that 9a18081 is the only commit in 1.37.18, and 1.37.17 is working.

**Comment by kripken** [comment]
Thanks! Ok, looking into this, the breakage is because comparing threads broke in single-threaded mode. Fix in https://github.com/kripken/emscripten/pull/5487
