### ISSUE TITLE
parse exception in node.js binaryen

### ISSUE THREAD

**Issue by pannous** [WebAssembly/binaryen#1416]
A wasm module works fine in the console but can't be parsed in node.js:
```
echo '(module
 (type $0 (func (result i32)))
 (table 1 1 anyfunc)
 (memory $0 2)
 (export "memory" (memory $0))
 (export "main" (func $0))
 (func $0 (type $0) (result i32)
  (i32.const 42)
 )
)' > foo.wast
wasm-as  foo.wast  
wasmx foo.wasm
>>> 42
node
> binaryen=require('binaryen')
> binaryen.readBinary('foo.wasm')
[parse exception: surprising value (at 0:4)]
Fatal: error in parsing wasm binary
Error
    at /opt/binaryen/bin/binaryen.js:130:197
    at Object.<anonymous> (/opt/binaryen/bin/binaryen.js:208:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

**Comment by kripken** [comment]
[readBinary](https://github.com/WebAssembly/binaryen/wiki/binaryen.js-API#module-construction) receives the actual binary data, not the filename.

Btw, what is "wasmx"?

**Comment by pannous** [comment]
oh sorry, stupid mistake.

wasmx is a little program which executes wasm's main method

**Comment by kripken** [comment]
Interesting, is wasmx a standalone project? Or is it part of something? I never heard of it til now.

**Comment by pannous** [comment]
embarrassingly it's a little helper I wrote a while ago.

```
function wasmx(){
  node -r ~/.wasm.js -e "wasm('$1').then(y=>{log(y);process.exit()}).catch(x=>{log(x);throw x})"
}

~/.wasm.js :
wasm = async (_wasm, imports = {}) => {
	if (is_file(_wasm)) _wasm = fs.readFileSync(_wasm)
	else _wasm = new Uint8Array(_wasm)
	module = await WebAssembly.compile(_wasm)
	instance = await WebAssembly.instantiate(module, imports)
        instance.exports.main()
}
```

sure warrents a proper node module ;)

**Comment by kripken** [comment]
Heh, thanks, now I see :)
