### ISSUE TITLE
the aarch64-linux releases contains x86-64 binaries

### ISSUE THREAD

**Issue by sivteck** [WebAssembly/binaryen#1615]
The [aarch64-linux](https://github.com/WebAssembly/binaryen/releases/download/1.38.6/binaryen-1.38.6-aarch64-linux.tar.gz) builds contains x86-64 binaries

```
$ file ./asm2wasm
./asm2wasm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

resulting in the following error when trying to compile with emcc

```
$ emcc emjs.cc -o index.html
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/usr/lib/emscripten/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/usr/lib/emscripten/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/usr/lib/emscripten/emcc.py", line 1937, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/usr/lib/emscripten/emcc.py", line 2408, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/sivpi/binaryen-1.38.6/bin/asm2wasm'
```

It also seems armhf builds have the same issue having x86-64 binaries

tagging @jirutka https://github.com/WebAssembly/binaryen/pull/1064

**Comment by nth10sd** [comment]
On aarch64 Ubuntu:

```
$ file binaryen-version_118/bin/wasm-opt
binaryen-version_118/bin/wasm-opt: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, BuildID[sha1]=4cef36d2f44dd7d7502558ea4040b1220c291ac8, stripped
```

@kripken I guess this is now resolved?

**Comment by kripken** [comment]
Thanks @nth10sd , yes, let's close this.
