### ISSUE TITLE
EMULATE_FUNCTION_POINTER_CASTS=1 + BINARYEN_TRAP_MODE=clamp

### ISSUE THREAD

**Issue by seshness** [WebAssembly/binaryen#1632]
I found some strange behaviour while working with datetimes on a proprietary codebase that embeds Python. I've distilled this into a standalone, reproducible example:

```c++
/* double-to-int.c */
#include <assert.h>
#include <stdio.h>
#include <stdint.h>

int main() {
  double d = 1451520000000.000000;
  printf("d = %f\n", d);
  int64_t i = (int64_t) d; // cast from double -> int64_t
  printf("i = %lld\n", i);
  assert(1451520000000 == i);
  return 0;
}
```

**Steps to repro**

1. `emcc -g4 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s BINARYEN_TRAP_MODE=clamp double-int-cast.c -o double-int-cast.js`
2. `node double-int-cast.js`

**Expected**
```
d = 1451520000000.000000
i = 1451520000000
```

**Actual**
```
d = 1451520000000.000000
i = 1447403978752
Assertion failed: 1451520000000 == i, at: double-int-cast.c,10,main
Assertion failed: 1451520000000 == i, at: double-int-cast.c,10,main
exception thrown: abort("Assertion failed: 1451520000000 == i, at: double-int-cast.c,10,main") at Error
    at jsStackTrace (/tmp/double-int-cast.js:1061:13)
    at stackTrace (/tmp/double-int-cast.js:1078:12)
    at abort (/tmp/double-int-cast.js:2506:44)
    at ___assert_fail (/tmp/double-int-cast.js:1815:7)
    at _main (wasm-function[23]:362)
    at Object.callMain (/tmp/double-int-cast.js:2350:30)
    at doRun (/tmp/double-int-cast.js:2408:60)
    at run (/tmp/double-int-cast.js:2422:5)
    at Object.<anonymous> (/tmp/double-int-cast.js:2533:1)
    at Module._compile (module.js:635:30)
```

**Environment**
emsdk at version `sdk-1.38.11-64bit`
macOS 10.13.5

**Notes**
When compiled with
`emcc -g4 -s BINARYEN_TRAP_MODE=clamp double-int-cast.c -o double-int-cast.js`
I see the snippet in **Expected**.

Why does `-s EMULATE_FUNCTION_POINTER_CASTS=1` affect this code?

I'm able to work around this using
```
-s EMULATE_FUNCTION_POINTER_CASTS=1 -s BINARYEN_TRAP_MODE=js
```
---

I took a look at the difference in the wasm builds using `wasm2wat`:
without emulating function pointer casts:
```
  ;;@ double-int-cast.c:8:0
  (set_local $$4
   (get_local $$1)
  )
  (set_local $$5
   (call $f64-to-int64
    (get_local $$4)
   )
  )
...
``` 

with `EMULATE_FUNCTION_POINTER_CASTS=1`:
```
  ;;@ double-int-cast.c:8:0
  (set_local $$4
   (get_local $$1)
  )
  (set_local $$5
   (call $f64-to-uint
    (get_local $$4)
   )
  )
...
```

Thanks in advance!

**Comment by kripken** [comment]
Looking into this some more, there isn't an easy fix. A complicated one is possible, but given this is for non-wasm-only mode, which is less important, and that both wasm-only and non-wasm-only modes will be deprecated anyhow once the LLVM wasm backend is the default, I'm not sure this is worth focusing on.

Instead, I'd recommend we document that the `js` trap mode is recommended when in non-wasm-only mode. Maybe we should even suggest it by the compiler if it's not set?

**Comment by seshness** [comment]
Thanks for looking into this, and for the explanations! We'll use the `js` trap mode for now.

Will the LLVM wasm backend support, or even need, something like `EMULATE_FUNCTION_POINTER_CASTS`?

I might be wildly off base here, but is there a way to isolate the effect of `EMULATE_FUNCTION_POINTER_CASTS` to, say, the few libraries like Python that require it, without forcing that flag on the linking of the final executable?
I suspect not from grepping for `EMULATE_FUNCTION_POINTER_CASTS`, and trying to understand how it works.

**Comment by tlively** [comment]
If this is still relevant on modern Emscripten, please open an issue on the Emscripten repo.
