### ISSUE TITLE
Why does it not pass the emcc WASM_BACKEND testcase when I run ./check.py

### ISSUE THREAD

**Issue by ppopth** [WebAssembly/binaryen#199]
Before I starting reading the code and trying to contribute to the project, should I care if it will pass all the tests ?

```
  (check in node)
.. indirect_call.cpp
....test/emscripten/emcc -o a.wasm.js -s BINARYEN="/home/haxxpop/Projects/WebAssembly/binaryen" test/wasm_backend/indirect_call.cpp -O1 -s ONLY_MY_CODE=1

  (check in node)
Traceback (most recent call last):
  File "./check.py", line 499, in <module>
    fail(out, expected)
  File "./check.py", line 126, in fail
    ''.join([a.rstrip()+'\n' for a in difflib.unified_diff(expected.split('\n'), actual.split('\n'), fromfile='expected', tofile='actual')])[-1000:]
Exception: incorrect output, diff:

--- expected
+++ actual
@@ -1,24 +1,25 @@
 print: argc : 1
-print: addr of something : 0
-print: addr of more : 1
+print: addr of something : 1
+print: addr of more : 2
 print: i : 0
-print: curr address to call : 0
+print: curr address to call : 1
 print: something : 12
 print: i : 1
-print: curr address to call : 1
+print: curr address to call : 2
 print: more : -1
 print: i : 2
-print: curr address to call : 0
+print: curr address to call : 1
 print: something : 12
 print: i : 3
-print: curr address to call : 1
+print: curr address to call : 2
 print: more : -1
+print: curr : 1
+print: other : 40
 print: curr : 2
-print: other : 40
-print: curr : 3
 print: yet : 100
+print: curr : 1
+print: other : 42
 print: curr : 2
-print: other : 42
-print: curr : 3
 print: yet : 102
+
```

**Comment by kripken** [comment]
Yes, that should pass.

Does the output mention any warnings? (can grep for `warning` in the output)

Are all submodules up to date? (`git submodule update`)

**Comment by haxxpop** [comment]
Oh sorry, it's in the beginning of stdout so I didn't notice that.
```
warning: no interpreter provided (did not test spec interpreter validation)
warning: no mozjs found (did not check asm.js validation)
```

**Comment by kripken** [comment]
Those just mean fewer tests were run. So it's very strange that that fails.

What OS are you on?

**Comment by haxxpop** [comment]
All submodules are up to date
Ubuntu 15.10

**Comment by kripken** [comment]
64 or 32 bit?

**Comment by haxxpop** [comment]
64bit

**Comment by haxxpop** [comment]
I use everything from http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

**Comment by haxxpop** [comment]
```
The following precompiled tool packages are available for download:
           node-4.1.1-32bit         
     *     node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        

The following tools can be compiled from source:
           clang-tag-e1.35.22-32bit 
           clang-tag-e1.35.23-32bit 
           clang-tag-e1.35.22-64bit 
           clang-tag-e1.35.23-64bit 
           clang-incoming-32bit     
     *     clang-incoming-64bit     	INSTALLED
           clang-master-32bit       
           clang-master-64bit       
           emscripten-tag-1.35.22-32bit
           emscripten-tag-1.35.23-32bit
           emscripten-tag-1.35.22-64bit
           emscripten-tag-1.35.23-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
     *     emscripten-incoming-64bit	INSTALLED
           emscripten-master-64bit  

The following precompiled SDKs are available for download:

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
    *    sdk-incoming-64bit       	INSTALLED
         sdk-master-32bit         
         sdk-master-64bit         
         sdk-tag-1.35.22-32bit    
         sdk-tag-1.35.23-32bit    

Items marked with * are activated for the current user.

To access the historical archived versions, type 'emsdk list --old'
```

**Comment by kripken** [comment]
That should be ok. And the Travis CI stuff is 64-bit ubuntu as well, and it passes, so I'm puzzled why it fails for you.

Try very latest master, perhaps, if you haven't already?

**Comment by haxxpop** [comment]
I'm trying. My laptop is frozen now due to the compilation :)

**Comment by haxxpop** [comment]
Do I need to run `auto_update_tests.py` ?

**Comment by kripken** [comment]
No, that is just when we change the code in ways that affects test output. What you are seeing appears to be a bug.

If it's still a problem after the update, can you create a gist with the file outputs in the breaking test? Then I can compare to what I and the bots get.

**Comment by haxxpop** [comment]
When I remove this test, it passes all other tests and everything is fine.
I'm not sure what happen with this test case.
https://gist.github.com/haxxpop/59840116dda4f16f5f06

**Comment by kripken** [comment]
Can you please add the code files too? It should generate `a.wasm.js`, and possibly some other files beginning with `a.wasm.*` (look at the dates).
