### ISSUE TITLE
[wasm-merge] Assertion failed in InputMergeable::visitGetGlobal() in wasm-merge.cpp

### ISSUE THREAD

**Issue by pventuzelo** [WebAssembly/binaryen#2165]
### Environment

| Questions            | Answers
|----------------------|--------------------
| Related Binary       | wasm-merge
| Commit               | commit 616abe47020c90278eaf8d14ae9815c31d2d14fb 

### Vulnerability/issue

Assertion failed in InputMergeable::visitGetGlobal() in wasm-merge.cpp

### Steps to reproduce the behavior 
- Download: [wasm-merge_assert_InputMergeable_visitGetGlobal.zip](https://github.com/WebAssembly/binaryen/files/3264924/wasm-merge_assert_InputMergeable_visitGetGlobal.zip)

- Run: `wasm-merge wasm-merge_assert_InputMergeable_visitGetGlobal wasm-merge_assert_InputMergeable_visitGetGlobal`

### Additional Informations

Crash
```
wasm-merge: XYZ/binaryen/src/tools/wasm-merge.cpp:319: void InputMergeable::visitGetGlobal(wasm::GetGlobal*): Assertion `curr->name.is()' failed.
```

GDB output
```
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/wasm-merge...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
wasm-merge: XYZ/binaryen/src/tools/wasm-merge.cpp:319: void InputMergeable::visitGetGlobal(wasm::GetGlobal*): Assertion `curr->name.is()' failed.

Program received signal SIGABRT, Aborted.

[----------------------------------registers-----------------------------------]
RAX: 0x0 
RBX: 0x0 
RCX: 0x7ffff6cbde97 (<__GI_raise+199>:	mov    rcx,QWORD PTR [rsp+0x108])
RDX: 0x0 
RSI: 0x7fffffffcd20 --> 0x0 
RDI: 0x2 
RBP: 0x7ffff6e367d8 ("%s%s%s:%u: %s%sAssertion `%s' failed.\n%n")
RSP: 0x7fffffffcd20 --> 0x0 
RIP: 0x7ffff6cbde97 (<__GI_raise+199>:	mov    rcx,QWORD PTR [rsp+0x108])
R8 : 0x0 
R9 : 0x7fffffffcd20 --> 0x0 
R10: 0x8 
R11: 0x246 
R12: 0x55555587f560 ("XYZ/binaryen/src/tools/wasm-merge.cpp")
R13: 0x55555587f5b6 ("curr->name.is()")
R14: 0x13f 
R15: 0x7fffffffd3e8 --> 0x555555b252e0 --> 0x5555556260c0 (<_ZN4wasm21ExpressionStackWalkerI14InputMergeableNS_7VisitorIS1_vEEE11doPostVisitEPS1_PPNS_10ExpressionE>:	push   rbp)
EFLAGS: 0x246 (carry PARITY adjust ZERO sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff6cbde8b <__GI_raise+187>:	mov    edi,0x2
   0x7ffff6cbde90 <__GI_raise+192>:	mov    eax,0xe
   0x7ffff6cbde95 <__GI_raise+197>:	syscall 
=> 0x7ffff6cbde97 <__GI_raise+199>:	mov    rcx,QWORD PTR [rsp+0x108]
   0x7ffff6cbde9f <__GI_raise+207>:	xor    rcx,QWORD PTR fs:0x28
   0x7ffff6cbdea8 <__GI_raise+216>:	mov    eax,r8d
   0x7ffff6cbdeab <__GI_raise+219>:	jne    0x7ffff6cbdecc <__GI_raise+252>
   0x7ffff6cbdead <__GI_raise+221>:	add    rsp,0x118
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffcd20 --> 0x0 
0008| 0x7fffffffcd28 --> 0x555555b489d0 --> 0x0 
0016| 0x7fffffffcd30 --> 0x7fffffffd3e8 --> 0x555555b252e0 --> 0x5555556260c0 (<_ZN4wasm21ExpressionStackWalkerI14InputMergeableNS_7VisitorIS1_vEEE11doPostVisitEPS1_PPNS_10ExpressionE>:	push   rbp)
0024| 0x7fffffffcd38 --> 0x7ffff6d075e0 (<_IO_vasprintf+240>:	test   rax,rax)
0032| 0x7fffffffcd40 --> 0xfbad8000 
0040| 0x7fffffffcd48 --> 0x555555b489d0 --> 0x0 
0048| 0x7fffffffcd50 --> 0x555555b48a35 (": void InputMergeable::visitGetGlobal(wasm::GetGlobal*): Assertion `curr->name.is()' failed.\n")
0056| 0x7fffffffcd58 --> 0x555555b489d0 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGABRT
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cbf801 in __GI_abort () at abort.c:79
#2  0x00007ffff6caf39a in __assert_fail_base (
    fmt=0x7ffff6e367d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x55555587f5b6 "curr->name.is()", 
    file=file@entry=0x55555587f560 "XYZ/binaryen/src/tools/wasm-merge.cpp", line=line@entry=0x13f, 
    function=function@entry=0x55555587e440 <InputMergeable::visitGetGlobal(wasm::GetGlobal*)::__PRETTY_FUNCTION__> "void InputMergeable::visitGetGlobal(wasm::GetGlobal*)") at assert.c:92
#3  0x00007ffff6caf412 in __GI___assert_fail (assertion=0x55555587f5b6 "curr->name.is()", 
    file=0x55555587f560 "XYZ/binaryen/src/tools/wasm-merge.cpp", line=0x13f, 
    function=0x55555587e440 <InputMergeable::visitGetGlobal(wasm::GetGlobal*)::__PRETTY_FUNCTION__> "void InputMergeable::visitGetGlobal(wasm::GetGlobal*)") at assert.c:101
#4  0x000055555562b2c3 in wasm::Walker<InputMergeable, wasm::Visitor<InputMergeable, void> >::doVisitGetGlobal(InputMergeable*, wasm::Expression**) ()
#5  0x000055555562fedc in InputMergeable::merge() ()
#6  0x000055555561f255 in main ()
#7  0x00007ffff6ca0b97 in __libc_start_main (main=0x55555561e750 <main>, argc=0x3, 
    argv=0x7fffffffdd48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd38) at ../csu/libc-start.c:310
#8  0x000055555562317a in _start ()
```

**Comment by kripken** [comment]
I assume the command `wasm-merge wasm-merge_assert_InputMergeable_visitGetGlobal wasm-merge_assert_InputMergeable_visitGetGlobal` needs `.wasm` on both input files? Even with that, though, I can't reproduce this problem, it exits without an error.

**Comment by pventuzelo** [comment]
Oh my bad, i mixed up in my configuration/compilation.
Not valid in this commit. 
Sorry for the time lost
