### ISSUE TITLE
[wasm-merge] SIGABRT (Memory allocation error) in wasm::WasmBinaryBuilder::readUserSection()

### ISSUE THREAD

**Issue by pventuzelo** [WebAssembly/binaryen#2166]
### Environment

| Questions            | Answers
|----------------------|--------------------
| Related Binary       | wasm-merge
| Commit               | commit 616abe47020c90278eaf8d14ae9815c31d2d14fb 

### Vulnerability/issue/problem

SIGABRT (Memory allocation error) in wasm::WasmBinaryBuilder::readUserSection()

### Steps to reproduce the behavior 
- Download: [wasm-merge_SIGABRT_bad_alloc.zip](https://github.com/WebAssembly/binaryen/files/3265340/wasm-merge_SIGABRT_bad_alloc.zip)

- Run: `./bin/wasm-merge wasm-merge_SIGABRT_bad_alloc.wasm wasm-merge_SIGABRT_bad_alloc.wasm`

### Additional Informations

Crash
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    14489 abort      ./bin/wasm-merge wasm-merge_SIGABRT_bad_alloc.wasm 
```

GDB output
```
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/wasm-merge...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.

[----------------------------------registers-----------------------------------]
RAX: 0x0 
RBX: 0x7ffff7980ce2 ("std::bad_alloc")
RCX: 0x7ffff6cbde97 (<__GI_raise+199>:	mov    rcx,QWORD PTR [rsp+0x108])
RDX: 0x0 
RSI: 0x7fffffffc930 --> 0x0 
RDI: 0x2 
RBP: 0x7ffff706b840 --> 0x7ffff706b680 --> 0xfbad2887 
RSP: 0x7fffffffc930 --> 0x0 
RIP: 0x7ffff6cbde97 (<__GI_raise+199>:	mov    rcx,QWORD PTR [rsp+0x108])
R8 : 0x0 
R9 : 0x7fffffffc930 --> 0x0 
R10: 0x8 
R11: 0x246 
R12: 0x555555b2d810 --> 0x0 
R13: 0x555555b2d760 --> 0x0 
R14: 0x0 
R15: 0xfffffffffffffffd
EFLAGS: 0x246 (carry PARITY adjust ZERO sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff6cbde8b <__GI_raise+187>:	mov    edi,0x2
   0x7ffff6cbde90 <__GI_raise+192>:	mov    eax,0xe
   0x7ffff6cbde95 <__GI_raise+197>:	syscall 
=> 0x7ffff6cbde97 <__GI_raise+199>:	mov    rcx,QWORD PTR [rsp+0x108]
   0x7ffff6cbde9f <__GI_raise+207>:	xor    rcx,QWORD PTR fs:0x28
   0x7ffff6cbdea8 <__GI_raise+216>:	mov    eax,r8d
   0x7ffff6cbdeab <__GI_raise+219>:	jne    0x7ffff6cbdecc <__GI_raise+252>
   0x7ffff6cbdead <__GI_raise+221>:	add    rsp,0x118
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffc930 --> 0x0 
0008| 0x7fffffffc938 --> 0x0 
0016| 0x7fffffffc940 --> 0x0 
0024| 0x7fffffffc948 --> 0x0 
0032| 0x7fffffffc950 --> 0x0 
0040| 0x7fffffffc958 --> 0x0 
0048| 0x7fffffffc960 ("std::bad_alloc")
0056| 0x7fffffffc968 --> 0x636f6c6c615f ('_alloc')
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGABRT
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cbf801 in __GI_abort () at abort.c:79
#2  0x00007ffff78d1957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff78d7ab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff78d7af1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff78d7d24 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff78d829c in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055555565a35f in std::vector<char, std::allocator<char> >::_M_default_append(unsigned long) ()
#8  0x000055555565204f in wasm::WasmBinaryBuilder::readUserSection(unsigned long) ()
#9  0x000055555565935b in wasm::WasmBinaryBuilder::read() ()
#10 0x000055555565fc3e in wasm::ModuleReader::readBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&) ()
#11 0x0000555555660377 in wasm::ModuleReader::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&) ()
#12 0x000055555561eff4 in main ()
#13 0x00007ffff6ca0b97 in __libc_start_main (main=0x55555561e750 <main>, argc=0x3, 
    argv=0x7fffffffdd48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd38) at ../csu/libc-start.c:310
#14 0x000055555562317a in _start ()
```

Valgring output
``` 
==8070== Memcheck, a memory error detector
==8070== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==8070== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==8070== Command: ./bin/wasm-merge wasm-merge_SIGABRT_bad_alloc.wasm wasm-merge_SIGABRT_bad_alloc.wasm
==8070== 
==8070== Argument 'size' of function __builtin_new has a fishy (possibly negative) value: -3
==8070==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8070==    by 0x20E35E: std::vector<char, std::allocator<char> >::_M_default_append(unsigned long) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x20604E: wasm::WasmBinaryBuilder::readUserSection(unsigned long) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x20D35A: wasm::WasmBinaryBuilder::read() (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x213C3D: wasm::ModuleReader::readBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x214376: wasm::ModuleReader::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x1D2FF3: main (in XYZ/binaryen/bin/wasm-merge)
==8070== 
**8070** new/new[] failed and should throw an exception, but Valgrind
**8070**    cannot throw exceptions and so is aborting instead.  Sorry.
==8070==    at 0x4C2F81C: ??? (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8070==    by 0x4C301F5: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8070==    by 0x20E35E: std::vector<char, std::allocator<char> >::_M_default_append(unsigned long) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x20604E: wasm::WasmBinaryBuilder::readUserSection(unsigned long) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x20D35A: wasm::WasmBinaryBuilder::read() (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x213C3D: wasm::ModuleReader::readBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x214376: wasm::ModuleReader::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&) (in XYZ/binaryen/bin/wasm-merge)
==8070==    by 0x1D2FF3: main (in XYZ/binaryen/bin/wasm-merge)
==8070== 
==8070== HEAP SUMMARY:
==8070==     in use at exit: 29,026 bytes in 573 blocks
==8070==   total heap usage: 696 allocs, 123 frees, 127,135 bytes allocated
==8070== 
==8070== LEAK SUMMARY:
==8070==    definitely lost: 0 bytes in 0 blocks
==8070==    indirectly lost: 0 bytes in 0 blocks
==8070==      possibly lost: 0 bytes in 0 blocks
==8070==    still reachable: 29,026 bytes in 573 blocks
==8070==         suppressed: 0 bytes in 0 blocks
==8070== Rerun with --leak-check=full to see details of leaked memory
==8070== 
==8070== For counts of detected and suppressed errors, rerun with: -v
==8070== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by kripken** [comment]
Hmm, I see
```
[parse exception: bad user section size (at 0:77)]
```
which looks like a proper error. Same in valgrind.

**Comment by pventuzelo** [comment]
Oh my bad, i mixed up in my configuration/compilation.
Not valid in this commit. 
Sorry for the time lost
