### ISSUE TITLE
Latest version (93) missing function: $stackTrace

### ISSUE THREAD

**Issue by TJKoury** [WebAssembly/binaryen#2861]
Building using the most recent version (93) crashes with the following error message:

```
missing function: $stackTrace
-1
missing function: $stackTrace
-1
...

missing function: $stackTrace
-1
/tmp/tmp_shptO.js:126
      throw ex;
      ^

RangeError: Maximum call stack size exceeded
    at Object.Console.<computed> (internal/console/constructor.js:259:9)
    at Object.warn (internal/console/constructor.js:305:26)
    at stackTrace (/tmp/tmp_shptO.js:1854:3)
    at abort (/tmp/tmp_shptO.js:1631:44)
    at stackTrace (/tmp/tmp_shptO.js:1854:41)
    at abort (/tmp/tmp_shptO.js:1631:44)
    at stackTrace (/tmp/tmp_shptO.js:1854:41)
    at abort (/tmp/tmp_shptO.js:1631:44)
    at stackTrace (/tmp/tmp_shptO.js:1854:41)
    at abort (/tmp/tmp_shptO.js:1631:44)
```

Downgrading to version 91 works as expected.

**Comment by kripken** [comment]
I believe @sbc100 recently fixed this. Was 93 tagged during the broken period perhaps?

Do we tag those with tot builds, or releases? This should not have reached a release, but IIRC we tag manually, and maybe used a tot, do you know @sbc100 ?

**Comment by sbc100** [comment]
Can I ask excactly what version of emscripten and binaryen you are using?  And what is failing here?  Is this your program, or is it generating the struct_info (something that happens during the build).

On ToT, these functions are now part of emscripten's compiler-rt.    Gut these were only removed from binaryen on ToT: #2852  (yesterfay).   That change is not part of a binaryen release.

There was an issue with ToT emscripten when building struct_info.  That was fixed in https://github.com/emscripten-core/emscripten/pull/11192.    But again the emscripten-side changes in this area is not part of any releaase yet.   1.39.16 doesn't have any of these changes AFAICT.

**Comment by ricardo-0x07** [comment]
Hi guys i'm struggling with this issue trying how downgrade the binaryen that is in emscripten

**Comment by sbc100** [comment]
@ricardo-0x07, if you use emsdk to install emscripten then the versions are guaranteed to be compatible.

**Comment by tlively** [comment]
Closing because it sounds like this should not be an issue in recent releases.
