### ISSUE TITLE
scripts/test/asm2wasm.py TypeError: a bytes-like object is required, not 'str' with --interpreter

### ISSUE THREAD

**Issue by rathann** [WebAssembly/binaryen#2974]
I'm getting this exception when running the asm2wasm testuite for version 95 with `wasm-interp` interpreter from [wabt](https://github.com/WebAssembly/wabt) .

```
$ ./check.py --binaryen-bin x86_64-redhat-linux-gnu/bin --interpreter /usr/bin/wasm-interp asm2wasm
warning: no mozjs found (did not check native wasm support nor asm.js validation)
[ using wasm interpreter at "/usr/bin/wasm-interp" ]
[ checking asm2wasm testcases... ]

.. bad_params.asm.js bad_params.fromasm.imprecise
With BINARYEN_PASS_DEBUG=1:
executing:  /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/asm2wasm /builddir/build/BUILD/binaryen-version_95/test/bad_params.asm.js --trap-mode=allow --ignore-implicit-traps -O
[PassRunner] running passes...
[PassRunner]   running pass: autodrop...                           1.4317e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: relooper-jump-threading...            9.987e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: ssa-nomerge...                        2.7238e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: dce...                                2.0185e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-brs...                  1.2711e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-names...                5.168e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: optimize-instructions...              9.429e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: pick-load-signs...                    6.774e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: precompute...                         1.8857e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: optimize-added-constants-propagate... 2.1441e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: code-pushing...                       1.341e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: simplify-locals-nostructure...        3.6528e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                             2.2908e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: reorder-locals...                     1.1874e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-brs...                  7.194e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: coalesce-locals...                    2.1861e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: simplify-locals...                    1.8648e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                             1.3479e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: reorder-locals...                     8.8e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: coalesce-locals...                    1.6762e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: reorder-locals...                     4.749e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                             1.299e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: code-folding...                       1.5994e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: merge-blocks...                       1.0616e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-brs...                  1.0057e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-names...                3.911e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: merge-blocks...                       4.819e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: precompute...                         1.0755e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: optimize-instructions...              8.66e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: rse...                                1.2223e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                             1.2362e-05 seconds.
[PassRunner]   (validating)
[PassRunner] passes took 0.000424707 seconds.
[PassRunner] (final validation)
[PassRunner] running passes...
[PassRunner]   running pass: memory-packing... 3.282e-06 seconds.
[PassRunner]   (validating)
[PassRunner] passes took 3.282e-06 seconds.
[PassRunner] (final validation)
[PassRunner] running passes...
[PassRunner]   running pass: finalize-calls...                 warning: asm2wasm adding operands in call from ex to missing (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm adding operands in call from ex to missing (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm dropping operands in call from ex to extra (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm dropping operands in call from ex to extra (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm adding operands in call from ex to mix (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm dropping operands in call from ex to mix (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
7.3822e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: legalize-js-interface...          4.051e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                         1.2082e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-brs...              8.032e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                         2.0533e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-names...            4.191e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: merge-blocks...                   6.985e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: optimize-instructions...          1.0755e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: post-emscripten...                9.0446e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: dae-optimizing...                 0.0011804 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: inlining-optimizing...            0.0127602 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: duplicate-function-elimination... 0.00292134 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: duplicate-import-elimination...   5.378e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: simplify-globals-optimizing...    0.00354796 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-module-elements...  1.0267e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: directize...                      2.235e-06 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: generate-stack-ir...              1.2152e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: optimize-stack-ir...              8.87e-06 seconds.
[PassRunner]   (validating)
[PassRunner] passes took 0.0206797 seconds.
[PassRunner] (final validation)
         (binary format check)
             /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/wasm-as /builddir/build/BUILD/binaryen-version_95/test/bad_params.fromasm.imprecise -o a.wasm -all -g
(skipping v8 binary validation)
             /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/wasm-dis a.wasm -o ab.wast
             /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/wasm-opt ab.wast -all
warning: no passes specified, not doing any work
warning: no output file specified, not emitting output
With BINARYEN_PASS_DEBUG disabled:
executing:  /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/asm2wasm /builddir/build/BUILD/binaryen-version_95/test/bad_params.asm.js --trap-mode=allow --ignore-implicit-traps -O
warning: asm2wasm adding operands in call from ex to missing (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm adding operands in call from ex to missing (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm dropping operands in call from ex to extra (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm dropping operands in call from ex to extra (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm adding operands in call from ex to mix (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
warning: asm2wasm dropping operands in call from ex to mix (this is likely due to undefined behavior in C, like defining a function one way and calling it in another, which is important to fix)
         (binary format check)
             /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/wasm-as /builddir/build/BUILD/binaryen-version_95/test/bad_params.fromasm.imprecise -o a.wasm -all -g
(skipping v8 binary validation)
             /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/wasm-dis a.wasm -o ab.wast
             /builddir/build/BUILD/binaryen-version_95/x86_64-redhat-linux-gnu/bin/wasm-opt ab.wast -all
warning: no passes specified, not doing any work
warning: no output file specified, not emitting output
Traceback (most recent call last):
  File "/builddir/build/BUILD/binaryen-version_95/scripts/test/asm2wasm.py", line 99, in test_asm2wasm
    reported = err.split(':')[1]
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/binaryen-version_95/./check.py", line 403, in <module>
    sys.exit(main())
  File "/builddir/build/BUILD/binaryen-version_95/./check.py", line 386, in main
    TEST_SUITES[test]()
  File "/builddir/build/BUILD/binaryen-version_95/scripts/test/asm2wasm.py", line 112, in test_asm2wasm
    shared.fail_with_error('wasm interpreter error: ' + err)
TypeError: can only concatenate str (not "bytes") to str
$ 
```

Is `wasm-interp` the correct interpreter?

**Comment by kripken** [comment]
I think we've only tested with the spec interpreter, not wabt's, so maybe that's the cause of the difference.

However, I don't think we've tested with the spec on either, for a long time - it was useful in the early days, but is less important now.

**Comment by rathann** [comment]
> I think we've only tested with the spec interpreter, not wabt's, so maybe that's the cause of the difference.

Where do I get the spec interpreter?

> However, I don't think we've tested with the spec one either, for a long time - it was useful in the early days, but is less important now.

So... should I just not bother and simply forget about this?

In any case, reading through the asm2wasm.py code, I found a example of wrong `subprocess.check_call` [usage](https://github.com/WebAssembly/binaryen/blob/master/scripts/test/asm2wasm.py#L91). Python documentation [explicitly says](https://docs.python.org/3/library/subprocess.html#subprocess.check_call) not to set `stdout=PIPE` or `stderr=PIPE` with this function.

**Comment by kripken** [comment]
The spec interpreter is in the main spec repo, under `/interpreter`, https://github.com/WebAssembly/spec/tree/master/interpreter

I'm not sure how much this matters. It might be simplest to just remove the spec integration if it's not used and not tested, and we can't think of a good reason for it atm - I can't, at least.

(Fixing `check_call` sounds like a good idea!)

**Comment by tlively** [comment]
asm2wasm and its tests no longer exist.
