### ISSUE TITLE
4 test failures on RHEL 7

### ISSUE THREAD

**Issue by rathann** [WebAssembly/binaryen#3002]
I'm getting 4 test failures when running the test suite on RHEL7 (`gcc-9.3.1` from devtoolset-9). Failing tests are:
* spec/names.wast
* wasm2js/comments.wast
* wasm2js/func_ptrs.wast
* unit/test_asyncify.py:AsyncifyTest

```
.. names.wast
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-shell /builddir/build/BUILD/binaryen-version
_95/test/spec/names.wast
       (using expected output)
        testing split module 0
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-shell split.wast
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-opt split.wast -O -all
         (binary format check)
             /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-as split.wast -o a.wasm -all -g
(skipping v8 binary validation)
             /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-dis a.wasm -o ab.wast
             /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-opt ab.wast -all
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-shell ab.wast
       (using expected output)
incorrect output, diff:

--- expected
+++ actual
@@ -1,2 +1 @@
-42 : i32
-123 : i32
+

...
.. comments.wast
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm2js split.wast -all --disable-exception-handling
No JS interpreters. Skipping spec tests.
incorrect output, diff:

--- /builddir/build/BUILD/binaryen-version_95/test/wasm2js/comments.2asm.js
+++ actual
@@ -29,33 +29,3 @@
 var memasmFunc = new ArrayBuffer(65536);
 var retasmFunc = asmFunc({Math,Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,NaN,Infinity}, {abort:function() { throw new Error('abort'); }},memasmFunc);

-function asmFunc(global, env, buffer) {
- var HEAP8 = new global.Int8Array(buffer);
- var HEAP16 = new global.Int16Array(buffer);
- var HEAP32 = new global.Int32Array(buffer);
- var HEAPU8 = new global.Uint8Array(buffer);
- var HEAPU16 = new global.Uint16Array(buffer);
- var HEAPU32 = new global.Uint32Array(buffer);
- var HEAPF32 = new global.Float32Array(buffer);
- var HEAPF64 = new global.Float64Array(buffer);
- var Math_imul = global.Math.imul;
- var Math_fround = global.Math.fround;
- var Math_abs = global.Math.abs;
- var Math_clz32 = global.Math.clz32;
- var Math_min = global.Math.min;
- var Math_max = global.Math.max;
- var Math_floor = global.Math.floor;
- var Math_ceil = global.Math.ceil;
- var Math_sqrt = global.Math.sqrt;
- var abort = env.abort;
- var nan = global.NaN;
- var infinity = global.Infinity;
- var FUNCTION_TABLE = [];
- return {
-
- };
-}
-
-var memasmFunc = new ArrayBuffer(65536);
-var retasmFunc = asmFunc({Math,Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,NaN,Infinity}, {abort:function() { throw new Error('abort'); }},memasmFunc);
-

...
.. func_ptrs.wast
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm2js split.wast -all --disable-exception-handl
ing
No JS interpreters. Skipping spec tests.
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm2js split.wast -all --disable-exception-handl
ing
No JS interpreters. Skipping spec tests.
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm2js split.wast -all --disable-exception-handl
ing
No JS interpreters. Skipping spec tests.
incorrect output, diff:

--- expected
+++ actual
@@ -1,2 +1 @@
-83 : i32


...
======================================================================
ERROR: test_asyncify_js (test.unit.test_asyncify.AsyncifyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/binaryen-version_95/test/unit/test_asyncify.py", line 19, in test_asyncify_js
    test(['-g'])
  File "/builddir/build/BUILD/binaryen-version_95/test/unit/test_asyncify.py", line 17, in test
    shared.run_process([shared.NODEJS, self.input_path('asyncify.js')])
  File "/builddir/build/BUILD/binaryen-version_95/scripts/test/shared.py", line 326, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib64/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

----------------------------------------------------------------------
Ran 50 tests in 2.153s

FAILED (errors=1)
```

**Comment by rathann** [comment]
RHEL7 is EOL, so I guess this is no longer relevant.
