### ISSUE TITLE
spec/names.wast test fails if executed on non-UTF-8 locale

### ISSUE THREAD

**Issue by rathann** [WebAssembly/binaryen#3003]
```
$ locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
$ python3 -V   
Python 3.6.8
$ ./check.py spec
...
.. names.wast
executing:  /builddir/build/BUILDROOT/binaryen-95-3.el7.x86_64/usr/bin/wasm-shell /builddir/build/BUILD/binaryen-version_95/test/spec/names.wast
'ascii' codec can't decode byte 0xef in position 1808: ordinal not in range(128)
Traceback (most recent call last):
  File "./check.py", line 223, in run_spec_tests
    actual = run_spec_test(wast)
  File "./check.py", line 199, in run_spec_test
    output = support.run_command(cmd, stderr=subprocess.PIPE)
  File "/builddir/build/BUILD/binaryen-version_95/scripts/test/support.py", line 173, in run_command
    out, err = proc.communicate()
  File "/usr/lib64/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 1578, in _communicate
    self.stderr.errors)
  File "/usr/lib64/python3.6/subprocess.py", line 760, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 1808: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./check.py", line 403, in <module>
    sys.exit(main())
  File "./check.py", line 386, in main
    TEST_SUITES[test]()
  File "./check.py", line 229, in run_spec_tests
    shared.fail_with_error(str(e))
  File "/builddir/build/BUILD/binaryen-version_95/scripts/test/shared.py", line 338, in fail_with_error
    raise Exception(msg)
Exception: 'ascii' codec can't decode byte 0xef in position 1808: ordinal not in range(128)
$
```

The following patch seems to help:
```diff
--- binaryen-version_95/scripts/test/support.py.orig    2020-07-21 06:04:33.000000000 +0200
+++ binaryen-version_95/scripts/test/support.py 2020-07-29 13:59:20.127904836 +0200
@@ -169,7 +169,7 @@ def run_command(cmd, expected_status=0,
             "Can't redirect stderr if using expected_err"
         stderr = subprocess.PIPE
     print('executing: ', ' '.join(cmd))
-    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=stderr, universal_newlines=True)
+    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=stderr, universal_newlines=True, encoding='UTF-8')
     out, err = proc.communicate()
     code = proc.returncode
     if expected_status is not None and code != expected_status:
```

**Comment by kripken** [comment]
I think that patch makes sense, although I'm not an expert on python encoding. A PR with that sounds good to land to me, would you like to open one?

**Comment by rathann** [comment]
Thanks for merging.
