### ISSUE TITLE
ReferenceError: ___cxa_find_matching_catch_2 is not defined

### ISSUE THREAD

**Issue by sps-gold** [WebAssembly/binaryen#3743]
Including flag INCLUDE_FULL_LIBRARY fails the build with:

ReferenceError: ___cxa_find_matching_catch_2 is not defined
    at Object.<anonymous> (/tmp/emscripten_test_other_enjwcv6n/test_split_module_ex.js:1:203814)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
-- end program output --
FAIL

https://github.com/emscripten-core/emscripten/pull/13696
test case: test_split_module_ex

**Comment by kripken** [comment]
(This also looks like it was filed in the wrong repo? Should be emscripten.)

**Comment by sps-gold** [comment]
sorry will move it to emscripten repo, closing here
