### ISSUE TITLE
Segfault in RemoveUnusedModuleElements::run

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/binaryen#3879]
When invoking with `--extract-function`.

Stack trace:
```
#0  0x00007fbb85826b06 in wasm::RemoveUnusedModuleElements::run(wasm::PassRunner*, wasm::Module*) ()
   from /usr/local/google/home/manoskouk/binaryen/bin/../lib/libbinaryen.so
#1  0x00007fbb8544baf4 in wasm::PassRunner::runPass(wasm::Pass*) ()
   from /usr/local/google/home/manoskouk/binaryen/bin/../lib/libbinaryen.so
#2  0x00007fbb8544c1d9 in wasm::PassRunner::run() ()
   from /usr/local/google/home/manoskouk/binaryen/bin/../lib/libbinaryen.so
#3  0x00007fbb855b12dd in wasm::ExtractFunction::run(wasm::PassRunner*, wasm::Module*) ()
   from /usr/local/google/home/manoskouk/binaryen/bin/../lib/libbinaryen.so
#4  0x00007fbb8544baf4 in wasm::PassRunner::runPass(wasm::Pass*) ()
   from /usr/local/google/home/manoskouk/binaryen/bin/../lib/libbinaryen.so
#5  0x00007fbb8544c1d9 in wasm::PassRunner::run() ()
   from /usr/local/google/home/manoskouk/binaryen/bin/../lib/libbinaryen.so
#6  0x00005638b07d08e0 in wasm::OptimizationOptions::runPasses(wasm::Module&) ()
#7  0x00005638b07be2ec in main ()
```

**Comment by kripken** [comment]
@manoskouk Hmm, there's not enough info in the stack trace for me to guess at the possible problem here. Can you send me the testcase+command?
