### ISSUE TITLE
Problem with run check.py on MacOS

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3998]
It seems script assume that all files in `/binaryen/bin` are executable but in some systems like MacOS filesystem can insert hidden aux files and caches like `.DS_Store`.

```bash
./check.py
[ checking --version ... ]

Parsed CHANGELOG.md version: 101

.. <path>/binaryen/bin/.DS_Store --version
Traceback (most recent call last):
  File " <path>/binaryen/./check.py", line 393, in <module>
    sys.exit(main())
  File " <path>/binaryen/./check.py", line 376, in main
    TEST_SUITES[test]()
  File " <path>binaryen/./check.py", line 54, in run_version_tests
    out, err = subprocess.Popen([e, '--version'],
  File " <path>/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File " <path>/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ' <path>/binaryen/bin/.DS_Store'
```

cc @tlively

**Comment by MaxGraey** [comment]
Hmm, after fixed this issue I got another one:
```
Parsed CHANGELOG.md version: 101

.. /Volumes/Archive/Projects/Github/binaryen/bin/asm2wasm --version
Traceback (most recent call last):
  File "<path>/binaryen/./check.py", line 393, in <module>
    sys.exit(main())
  File "<path>/binaryen/./check.py", line 376, in main
    TEST_SUITES[test]()
  File "<path>/binaryen/./check.py", line 59, in run_version_tests
    assert len(err) == 0, 'Expected no stderr, got:\n%s' % err
AssertionError: Expected no stderr, got:
dyld: Symbol not found: __ZN4wasm11GLOBAL_MATHE
  Referenced from: <path>/Github/binaryen/bin/asm2wasm
  Expected in:<path>/binaryen/bin/../lib/libbinaryen.dylib
 in <path>/binaryen/bin/asm2wasm
```

**Comment by MaxGraey** [comment]
It seems after delete non-relevant asm2wasm file got next problem =)
```bash
Unexpected type
UNREACHABLE executed at <path>/binaryen/src/wasm/wasm-type.cpp:1014!
Traceback (most recent call last):
  File "<path>/binaryen/./check.py", line 393, in <module>
    sys.exit(main())
  File "<path>/binaryen/./check.py", line 376, in main
    TEST_SUITES[test]()
  File "<path>/binaryen/scripts/test/wasm_opt.py", line 69, in test_wasm_opt
    curr = support.run_command(cmd)
  File "<path>/binaryen/scripts/test/support.py", line 182, in run_command
    raise Exception(('run_command failed (%s)' % code, out + str(err or '')))
Exception: ('run_command failed (-6)', '')

```

**Comment by kripken** [comment]
Does deleting `bin/*` and then rebuilding help?

**Comment by MaxGraey** [comment]
Unfortunately not. this issue https://github.com/WebAssembly/binaryen/issues/3998#issuecomment-881647853 still present

**Comment by MaxGraey** [comment]
As I understand problem with this line:
https://github.com/WebAssembly/binaryen/blob/main/scripts/binaryen-lit.in#L18

**Comment by MaxGraey** [comment]
It seems I just should install [`lit` package](https://pypi.org/project/lit/). Will be great describe this in README
