### ISSUE TITLE
Nominal types: Nondeterminism testcase

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#4082]
[a.wasm.gz](https://github.com/WebAssembly/binaryen/files/6985460/a.wasm.gz)

STR:
```
wasm-opt a.wasm --simplify-locals-nostructure --vacuum --dae --precompute --simplify-locals-nostructure --vacuum --dae -all --nominal --print > b1.wat
wasm-opt a.wasm --simplify-locals-nostructure --vacuum --dae --precompute --simplify-locals-nostructure --vacuum --dae -all --nominal --print > b2.wat
diff b1.wat b2.wat
```

This doesn't happen each time, but if I run those commands 30 times it always happens in at least one. The actual diff varies too, e.g.:
```diff
29d28
<  (type $none_=>_i64_externref_i32_externref_eqref_anyref (func (result i64 externref i32 externref eqref anyref)))
91a91,92
>  (type $none_=>_i64_externref_i32_externref_eqref_anyref (func (result i64 externref i32 externref eqref anyref)))
>  (type $none_=>_i64_externref_i32_externref_eqref_anyref (func (result i64 externref i32 externref eqref anyref)))
```
or
```diff
6d5
<  (type $f32_=>_none (func (param f32)))
7a7
>  (type $f32_=>_none (func (param f32)))
80a81
>  (type $f32_=>_none (func (param f32)))
```
This is not just a text format issue as writing to binary files also shows a difference.

@tlively

**Comment by kripken** [comment]
Perhaps related, fuzzing of nominal types also finds segfaults. ASan points to this:
```
    #6 0x7fe0ebb5fdec in wasm::(anonymous namespace)::Store<wasm::(anonymous namespace)::HeapTypeInfo>::hasCanonical(wasm::(anonymous namespace)::HeapTypeInfo const&, wasm::HeapType&) src/wasm/wasm-type.cpp 759:26                                                                                                                                                                    
    #7 0x7fe0ebb5f797 in wasm::HeapType::HeapType(wasm::Signature) src/wasm/wasm-type.cpp:1105:27                                                                      
    #8 0x7fe0e9ed717c in wasm::ModuleUtils::collectHeapTypes(wasm::Module&, std::vector<wasm::HeapType, std::allocator<wasm::HeapType> >&, std::unordered_map<wasm::HeapType, unsigned int, std::hash<wasm::HeapType>, std::equal_to<wasm::HeapType>, std::allocator<std::pair<wasm::HeapType const, unsigned int> > >&)::CodeScanner::visitExpression(wasm::Expression*) src/ir/module-utils.h 505:23                                                                                                                                                                                                     
```

That is indeed in code only reached by nominal typing, line 759 here:

https://github.com/WebAssembly/binaryen/blob/551b9dd9cd3c1194214a35e1b2a9d2f550577ff3/src/wasm/wasm-type.cpp#L757-L765

and 1105 here:

https://github.com/WebAssembly/binaryen/blob/551b9dd9cd3c1194214a35e1b2a9d2f550577ff3/src/wasm/wasm-type.cpp#L1100-L1110

I don't remember enough about type canonicalization in nominal mode, hoping this is something obvious to you @tlively ...

**Comment by tlively** [comment]
Hmm, I can reproduce the nondeterminism (and I got yet another diff). This does seem related to the segfaults, since it is the same line 505 in module-utils.h that produces the nondeterminism. Would you be able to find me a segfaulting test case to look at?

**Comment by kripken** [comment]
I don't recall if I saw a segfault on the wasm file here, but the segfault was pretty random so even if I happened to not see one on it, it might still be a potential testcase. As the nondeterminism happens much more consistently, maybe that's worth looking at first?

If you do prefer to focus on the segfault, they can be seen by running the fuzzer with this patch: https://github.com/WebAssembly/binaryen/compare/fuzznom?expand=1 it doesn't take that long to find them, usually a few thousand iterations. (You may need to disable the determinism fuzzer so that doesn't get hit earlier; also make sure to use latest `main` as the OptimizeInstructions fix for nominal types that landed today would also be found repeatedly.)

**Comment by kripken** [comment]
By "pretty random" I mean: after running for a few thousand iterations, I'd see a crash, but I'd not be able to reproduce that crash on that testcase even if I tried a few dozen more times. It's just very unlikely to happen even for a fixed workload, sadly.

**Comment by tlively** [comment]
Ahh got it. I think there is some sort of lifetime issue happening where the keys of the typeIDs map are being changed or overwritten. I guess it occasionally results in a segfault instead of an incorrect result.

**Comment by tlively** [comment]
Nominal types no longer exist and the type system implementation has been simplified a lot since this discussion, so it is almost certainly no longer relevant.
