### ISSUE TITLE
Invalid memory address dereference in wasm::HeapType::isSignature() const ()

### ISSUE THREAD

**Issue by ZFeiXQ** [WebAssembly/binaryen#4390]
**Version:**
```
version_103
```
**System information**
Ubuntu 20.04.1 LTS, clang version 10.0.0-4ubuntu1

**command:**
```
./bin/wasm-ctor-eval POC3
```

**Result**
```
[5]    1150289 segmentation fault  ./bin/wasm-ctor-eval 
```
**Gdb information**
```
Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x0 
RBX: 0x20 (' ')
RCX: 0x3 
RDX: 0x5555555dc110 --> 0x5555555e90c0 --> 0x0 
RSI: 0x5555555dc530 --> 0x5555555dc110 --> 0x5555555e90c0 --> 0x0 
RDI: 0x20 (' ')
RBP: 0x7fffffffcdd0 --> 0x7fffffffce00 --> 0x7fffffffcf20 --> 0x7fffffffcf90 --> 0x7fffffffd000 --> 0x7fffffffd060 (--> ...)
RSP: 0x7fffffffcdb8 --> 0x7ffff7c84705 (<_ZNK4wasm8HeapType12getSignatureEv+21>:	test   al,al)
RIP: 0x7ffff7c84384 (<_ZNK4wasm8HeapType11isSignatureEv+4>:	mov    rdx,QWORD PTR [rdi])
R8 : 0x2 
R9 : 0x5555555ea090 --> 0x360 
R10: 0x7ffff737079f ("_ZNK4wasm8HeapType11isSignatureEv")
R11: 0x7ffff7c84380 (<_ZNK4wasm8HeapType11isSignatureEv>:	endbr64)
R12: 0x7fffffffcde0 --> 0x7fffffffcf20 --> 0x7fffffffcf90 --> 0x7fffffffd000 --> 0x7fffffffd060 --> 0x7fffffffd130 (--> ...)
R13: 0x7fffffffced0 --> 0x5555555e87e0 --> 0x0 
R14: 0x7f 
R15: 0x7fffffffce88 --> 0x5555555e86b0 --> 0x555e7600 ('')
EFLAGS: 0x10206 (carry PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff7c84372:	data16 nop WORD PTR cs:[rax+rax*1+0x0]
   0x7ffff7c8437d:	nop    DWORD PTR [rax]
   0x7ffff7c84380 <_ZNK4wasm8HeapType11isSignatureEv>:	endbr64 
=> 0x7ffff7c84384 <_ZNK4wasm8HeapType11isSignatureEv+4>:	mov    rdx,QWORD PTR [rdi]
   0x7ffff7c84387 <_ZNK4wasm8HeapType11isSignatureEv+7>:	xor    eax,eax
   0x7ffff7c84389 <_ZNK4wasm8HeapType11isSignatureEv+9>:	cmp    rdx,0x5
   0x7ffff7c8438d <_ZNK4wasm8HeapType11isSignatureEv+13>:	jbe    0x7ffff7c84396 <_ZNK4wasm8HeapType11isSignatureEv+22>
   0x7ffff7c8438f <_ZNK4wasm8HeapType11isSignatureEv+15>:	cmp    DWORD PTR [rdx+0x10],0x1
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffcdb8 --> 0x7ffff7c84705 (<_ZNK4wasm8HeapType12getSignatureEv+21>:	test   al,al)
0008| 0x7fffffffcdc0 --> 0x0 
0016| 0x7fffffffcdc8 --> 0x0 
0024| 0x7fffffffcdd0 --> 0x7fffffffce00 --> 0x7fffffffcf20 --> 0x7fffffffcf90 --> 0x7fffffffd000 --> 0x7fffffffd060 (--> ...)
0032| 0x7fffffffcdd8 --> 0x7ffff7bd67fe (<_ZN4wasm8Function12getNumLocalsEv+46>:	mov    rdi,r12)
0040| 0x7fffffffcde0 --> 0x7fffffffcf20 --> 0x7fffffffcf90 --> 0x7fffffffd000 --> 0x7fffffffd060 --> 0x7fffffffd130 (--> ...)
0048| 0x7fffffffcde8 --> 0xc378056ac539f200 
0056| 0x7fffffffcdf0 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x00007ffff7c84384 in wasm::HeapType::isSignature() const () from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
gdb-peda$ bt
#0  0x00007ffff7c84384 in wasm::HeapType::isSignature() const () from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#1  0x00007ffff7c84705 in wasm::HeapType::getSignature() const () from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#2  0x00007ffff7bd67fe in wasm::Function::getNumLocals() () from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#3  0x00007ffff7bf4bee in wasm::WasmBinaryBuilder::pushExpression(wasm::Expression*) ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#4  0x00007ffff7c0afd0 in wasm::WasmBinaryBuilder::skipUnreachableCode() ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#5  0x00007ffff7c0b230 in wasm::WasmBinaryBuilder::processExpressions() ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#6  0x00007ffff7c0b3e6 in wasm::WasmBinaryBuilder::readExpression() ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#7  0x00007ffff7c0bd0a in wasm::WasmBinaryBuilder::readDataSegments() ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#8  0x00007ffff7c10f08 in wasm::WasmBinaryBuilder::read() () from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#9  0x00007ffff7c3ce46 in wasm::ModuleReader::readBinaryData(std::vector<char, std::allocator<char> >&, wasm::Module&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#10 0x00007ffff7c3d64c in wasm::ModuleReader::readBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#11 0x00007ffff7c3dd21 in wasm::ModuleReader::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wasm::Module&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
   from /home/zxq/CVE_testing/sourceproject/binaryen/bin/../lib/libbinaryen.so
#12 0x000055555556943e in main ()
#13 0x00007ffff6ec40b3 in __libc_start_main (main=0x5555555688c0 <main>, argc=0x2, argv=0x7fffffffe2e8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2d8) at ../csu/libc-start.c:308
#14 0x0000555555569e5e in _start ()

```

**Comment by ZFeiXQ** [comment]
[POC3.zip](https://github.com/WebAssembly/binaryen/files/7711619/POC3.zip)
