### ISSUE TITLE
[binaryen.js] ReferenceError: require is not defined

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#5071]
```
UnhandledPromiseRejectionWarning: ReferenceError: require is not defined
+    at file:///home/runner/work/binaryen/binaryen/out/test/a.mjs:19:64
+    at __in_test_code__ (file:///home/runner/work/binaryen/binaryen/out/test/a.mjs:613:34)
+    at file:///home/runner/work/binaryen/binaryen/out/test/a.mjs:703:11
+    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
+    at async Loader.import (internal/modules/esm/loader.js:178:24)
+    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by MaxGraey** [comment]
It looks like realte to https://github.com/emscripten-core/emscripten/pull/17851

**Comment by dcodeIO** [comment]
This is now worked around by #5075, where a `require` function has been added to the externs-pre file. More details towards an eventual fix on the linked Emscripten issue.
