### ISSUE TITLE
`wasm-opt` segfault with named memory and debug information

### ISSUE THREAD

**Issue by patrick96** [WebAssembly/binaryen#5204]
With the following minimal WAT file (stored as `test.wat`), `wasm-opt` crashes if assembled with debug information:

```wast
(module 
  (memory $mem0 100)
  (data (offset (i32.const 0)) "")
)
```

```bash
$ wasm-as -g test.wat # Also happens with wat2wasm --debug-names test.wat
$ wasm-opt test.wasm
[1]    2175877 segmentation fault (core dumped)  wasm-opt test.wasm
```

* `wasm-opt --version`: `wasm-opt version 110 (version_110)`
* `test.wasm`: [test.wasm.txt](https://github.com/WebAssembly/binaryen/files/9910628/test.wasm.txt)

---

I also reproduced this on `main` and got the following asan stack trace:

```
/home/paziegle/Projects/github.com/WebAssembly/binaryen/src/wasm/wasm-validator.cpp:3193:23: runtime error: member call on null pointer of type 'struct Memory'
/home/paziegle/Projects/github.com/WebAssembly/binaryen/src/wasm.h:2080:24: runtime error: member access within null pointer of type 'struct Memory'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2191171==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000050 (pc 0x56065791fa76 bp 0x7ffc7e40acc0 sp 0x7ffc7e40aca0 T0)
==2191171==The signal is caused by a READ memory access.
==2191171==Hint: address points to the zero page.
    #0 0x56065791fa76 in wasm::Type::operator==(wasm::Type::BasicType const&) const /home/paziegle/Projects/github.com/WebAssembly/binaryen/src/wasm-type.h:205
    #1 0x560657929925 in wasm::Memory::is64() (/home/paziegle/Projects/github.com/WebAssembly/binaryen/build/bin/wasm-opt+0x78d925)
    #2 0x7fc0217631f8 in validateDataSegments /home/paziegle/Projects/github.com/WebAssembly/binaryen/src/wasm/wasm-validator.cpp:3193
    #3 0x7fc021768eee in wasm::WasmValidator::validate(wasm::Module&, unsigned int) /home/paziegle/Projects/github.com/WebAssembly/binaryen/src/wasm/wasm-validator.cpp:3412
    #4 0x560657a8a544 in main /home/paziegle/Projects/github.com/WebAssembly/binaryen/src/tools/wasm-opt.cpp:289
    #5 0x7fc012e2350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #6 0x7fc012e235c8 in __libc_start_main_impl ../csu/libc-start.c:381
    #7 0x5606578519e4 in _start (/home/paziegle/Projects/github.com/WebAssembly/binaryen/build/bin/wasm-opt+0x6b59e4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/paziegle/Projects/github.com/WebAssembly/binaryen/src/wasm-type.h:205 in wasm::Type::operator==(wasm::Type::BasicType const&) const
==2191171==ABORTING
```

**Comment by tlively** [comment]
There are a few problems here:

1. The segfault in the validator. This is trivial to fix.
2. Somehow the memory is getting the name "mem0" emitted into the names section even though its internal name starts out as "0".
3. When the names section is read, we update the internal names of the named items, but we don't seem to update any references that used the old names. I'm not sure how this has ever worked correctly for anything, so I'm probably missing something.

**Comment by patrick96** [comment]
Appreciate it!
