### ISSUE TITLE
basic_string_view Assertion failed when running wasm-opt tests with GCC-12.2.1

### ISSUE THREAD

**Issue by rathann** [WebAssembly/binaryen#5342]
When building version 111 on Fedora development branch (rawhide) with GCC-12.2.1, I got assertion failed when **wasm-opt**-imizing `hello_world.wat`:
```
$ ./check.py --binaryen-bin /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin --binaryen-lib /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/lib64/binaryen
/usr/include/c++/12/string_view:239: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
[ checking --version ... ]

Parsed CHANGELOG.md version: 111

.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-as --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-ctor-eval --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-dis --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-emscripten-finalize --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-fuzz-types --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-metadce --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-reduce --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-shell --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-split --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm2js --version

[ checking wasm-opt -o notation... ]

executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt /builddir/build/BUILD/binaryen-version_111/test/hello_world.wat -o a.wat -S
Traceback (most recent call last):
  File "/builddir/build/BUILD/binaryen-version_111/./check.py", line 416, in <module>
    sys.exit(main())
             ^^^^^^
  File "/builddir/build/BUILD/binaryen-version_111/./check.py", line 399, in main
    TEST_SUITES[test]()
  File "/builddir/build/BUILD/binaryen-version_111/scripts/test/wasm_opt.py", line 31, in test_wasm_opt
    support.run_command(cmd)
  File "/builddir/build/BUILD/binaryen-version_111/scripts/test/support.py", line 182, in run_command
    raise Exception(('run_command failed (%s)' % code, out + str(err or '')))
Exception: ('run_command failed (-6)', '')
$
```

After applying 6658a66e6330f25105f0dca7241e520cffb8c3eb , I get a little bit further:
```
...
$ ./check.py --binaryen-bin /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin --binaryen-lib /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/lib64/binaryen
[ checking --version ... ]

Parsed CHANGELOG.md version: 111

.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-as --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-ctor-eval --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-dis --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-emscripten-finalize --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-fuzz-types --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-metadce --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-reduce --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-shell --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-split --version
.. /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm2js --version

[ checking wasm-opt -o notation... ]

executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt /builddir/build/BUILD/binaryen-version_111/test/hello_world.wat -o a.wat -S
warning: no passes specified, not doing any work
executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt /builddir/build/BUILD/binaryen-version_111/test/hello_world.wat -o a.wat -S --no-validation
warning: no passes specified, not doing any work

[ checking wasm-opt binary reading/writing... ]

executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt a.wat -o a.wasm
warning: no passes specified, not doing any work
executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt a.wasm -o b.wast -S
warning: no passes specified, not doing any work

[ checking wasm-opt passes... ]

.. O.wasm
executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt -O split.wast --print
warning: no output file specified, not emitting output
executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt -O split.wast --print --debug
executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt -O split.wast --print
.. O1_print-stack-ir.wast
executing:  /builddir/build/BUILDROOT/binaryen-111-1.fc38.x86_64/usr/bin/wasm-opt -O1 --print-stack-ir split.wast --print
/usr/include/c++/12/string_view:239: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
Traceback (most recent call last):
  File "/builddir/build/BUILD/binaryen-version_111/./check.py", line 416, in <module>
    sys.exit(main())
             ^^^^^^
  File "/builddir/build/BUILD/binaryen-version_111/./check.py", line 399, in main
    TEST_SUITES[test]()
  File "/builddir/build/BUILD/binaryen-version_111/scripts/test/wasm_opt.py", line 69, in test_wasm_opt
    curr = support.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/binaryen-version_111/scripts/test/support.py", line 182, in run_command
    raise Exception(('run_command failed (%s)' % code, out + str(err or '')))
Exception: ('run_command failed (-6)', '')
$
```

This looks related to #5322 , which I also get when running `binaryen-unittests` directly.

**Comment by rathann** [comment]
Confirmed fixed. Tests pass now on all 64-bit arches on Linux (Fedora rawhide).

**Comment by olivier-fs** [comment]
@rathann
Hi! That's interesting
Because now that #5322/#5342 are closed, on Win10 + VS 2019 I still hit the two failures that I reported in [#5291](https://github.com/WebAssembly/binaryen/issues/5291)

Now obviously IEEE 754 's FP32/FP64 arithmetic is a highly platform/os/hardware/numerical lib dependant matter...

It would be helpful if you could dump the 'lexer' and 'expected' contents on lines L1188 and 1195, to see what possible difference there might be here between Fedora's gcc+glibc and Windows' cl+msvcrtd/ucrtd.

**Comment by olivier-fs** [comment]
@rathann : That would have been e.g. setting a breakpoint in gdb and displaying local vars content.
But @tlively managed to quickly solve it in-between.
Thanks for caring anyway ;-)

Sorry I cannot help with #5353 because I have no 32bits toolchain available...

BTW is the memory error actually in python or in wasm-opt ?
Looks like a full python traceback, but an OOM in wasm-opt would also probably starve the parent python process...
