### ISSUE TITLE
use of uninitialized value in binaryen-shell

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#561]
Speaking of sanitizers, I was trying to reproduce the current leak failure on the travis build and got the following from msan:

```
.. coalesce-locals-learning.wast
executing:  bin/binaryen-shell --coalesce-locals-learning test/passes/coalesce-locals-learning.wast --print
Uninitialized bytes in __interceptor_fopen64 at offset 41 inside [0x70a00000e668, 42)
==51044==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f7c47dac9bf in std::__basic_file<char>::open(char const*, std::_Ios_Openmode, int) /build/gcc-4.8-mW1ufQ/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/src/c++98/basic_file.cc:238
    #1 0x7f7c47de4ea9 in std::basic_filebuf<char, std::char_traits<char> >::open(char const*, std::_Ios_Openmode) /build/gcc-4.8-mW1ufQ/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:99
    #2 0x7f7c47de6392 in std::basic_filebuf<char, std::char_traits<char> >::open(std::string const&, std::_Ios_Openmode) /build/gcc-4.8-mW1ufQ/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/include/fstream:281
    #3 0x7f7c47de6392 in std::basic_ifstream<char, std::char_traits<char> >::open(std::string const&, std::_Ios_Openmode) /build/gcc-4.8-mW1ufQ/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/include/fstream:560
    #4 0xadd4bb in std::vector<char, std::allocator<char> > wasm::read_file<std::vector<char, std::allocator<char> > >(std::string const&, wasm::Flags::BinaryOption, wasm::Flags::DebugOption) /s/wasm-waterfall/src/work/binaryen/src/support/file.cpp:28:3
    #5 0x5fbfa6 in main /s/wasm-waterfall/src/work/binaryen/src/tools/binaryen-shell.cpp:199:14
    #6 0x7f7c46e47f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #7 0x58a7c8 in _start (/usr/local/google/home/dschuff/s/wasm-waterfall/src/work/binaryen/bin/binaryen-shell+0x58a7c8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /build/gcc-4.8-mW1ufQ/gcc-4.8-4.8.4/build/x86_64-linux-gnu/libstdc++-v3/src/c++98/basic_file.cc:238 in std::__basic_file<char>::open(char const*, std::_Ios_Openmode, int)
```

**Comment by kripken** [comment]
Looks like this is deep inside stdc++ code, perhaps this is something new in your local version of stdc++ that needs to be added to a list of stuff to ignore?

Based on the stack trace, I also assume it's not specific to that pass, but would occur in any loading of a file in any of the tools, seems like a very broad issue in stdc++.

**Comment by dschuff** [comment]
Yeah, sorry, I was just running this before I left the office and wanted to get it recorded somewhere before I forgot about it. You're right, it doesn't look actionable and it's probably not new.
