### ISSUE TITLE
wasm2js --remove-imports flag not working

### ISSUE THREAD

**Issue by kuroahna** [WebAssembly/binaryen#6134]
```
> wasm-pack --version
wasm-pack 0.12.1

> wasm2js --version
wasm2js version 116
```

I have the following rust code

```rust
use wasm_bindgen::prelude::wasm_bindgen;

#[wasm_bindgen]
pub struct Rectangle {
    length: f64,
    width: f64,
}

#[wasm_bindgen]
impl Rectangle {
    pub fn new(length: f64, width: f64) -> Self {
        Self { length, width }
    }

    pub fn length(&self) -> f64 {
        self.length
    }

    pub fn width(&self) -> f64 {
        self.width
    }

    pub fn area(&self) -> f64 {
        self.length * self.width
    }
}
```

And compiled it using 
```
> wasm-pack build
> wasm2js --remove-imports pkg/hello_world_bg.wasm -o pkg/hello_world_bg.wasm.js
```

But the generated `pkg/hello_world_bg.wasm.js` file still imports

```js
import * as $_hello_world_bg_js from './hello_world_bg.js';
```

at the top. Is this expected?

I also would like to be able to run the generated JS file as a standalone without ES6 modules, so I added the `--emscripten` flag

```
wasm2js --emscripten --remove-imports pkg/hello_world_bg.wasm -o pkg/hello_world_bg.wasm.js
```

However, in the `asmFunc` function, it still references `./hello_world_bg.js` file

```js
function asmFunc(imports) {
 var buffer = new ArrayBuffer(1114112);
// ...
 var $_hello_world_bg_js = imports["./hello_world_bg.js"];
 var fimport$0 = $_hello_world_bg_js.__wbindgen_throw;
// ...
```

Adding
```js
const wasm = instantiate();
const rect = wasm.rectangle_new(2, 3);
console.log(wasm.rectangle_length(rect));
console.log(wasm.rectangle_width(rect));
console.log(wasm.rectangle_area(rect));
```
at the bottom of `pkg/hello_world_bg.wasm.js` and running `node pkg/hello_world_bg.wasm.js` throws the error

```
> node main.js
/Users/user1/test/hello_world/main.js:47
 var $_hello_world_bg_js = imports["./hello_world_bg.js"];
                                  ^

TypeError: Cannot read properties of undefined (reading './hello_world_bg.js')
    at asmFunc (/Users/user1/test/hello_world/main.js:47:35)
    at instantiate (/Users/user1/test/hello_world/main.js:2724:10)
    at Object.<anonymous> (/Users/user1/test/hello_world/main.js:2727:14)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.1.0
```

If I comment out the 2 lines

```
 var $_hello_world_bg_js = imports["./hello_world_bg.js"];
 var fimport$0 = $_hello_world_bg_js.__wbindgen_throw;
```

then it works

I also tried
```
> wasm-pack build --no-modules
> wasm2js --emscripten pkg/hello_world_bg.wasm -o pkg/hello_world_bg.wasm.js
```

but it still generates
```
 var wbg = imports.wbg;
 var fimport$0 = wbg.__wbindgen_throw;
```

I was hoping to have the contents of `hello_world_bg.js` and `hello_world_bg.wasm` compiled into 1 standalone js file to use, ie such as

```js
const rect = new Rectangle(2, 3);
console.log(rect.length);
console.log(rect.width);
console.log(rect.area);
```

but I'm not sure if this is possible.

For now, I'm okay with having to do

```js
const wasm = instantiate();
const rect = wasm.rectangle_new(2, 3);
console.log(wasm.rectangle_length(rect));
console.log(wasm.rectangle_width(rect));
console.log(wasm.rectangle_area(rect));
```

with the workaround of commenting out 
```
 var $_hello_world_bg_js = imports["./hello_world_bg.js"];
 var fimport$0 = $_hello_world_bg_js.__wbindgen_throw;
```

but it would be nice to have `--remove-imports` do this automatically

**Comment by kuroahna** [comment]
Nevermind, I was able to solve this by just running wasm directly instead of using wasm2js. I compile using

```
	wasm-pack build --release --no-typescript --no-pack --target no-modules
```

then I inline the wasm file in the autogenerated js script as a `Uint8Array` and load that instead
