### ISSUE TITLE
module[0]->str() == MODULE

### ISSUE THREAD

**Issue by rongjiecomputer** [WebAssembly/binaryen#692]
I tried to build the binaries from source in master branch with handcrafted batch script, no warning and error during compilation. But when I tried to run `asm2wasm -h`, I got assertion failed:

```
Assertion failed!

Program: C:\Users\jie\Downloads\binaryen-master\asm2wasm.exe
File: src/wasm-s-parser.h, Line 273

Expression: module[0]->str() == MODULE

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

The same applies to all other binaries regardless of what command arguments I used.

I am using mingw64 gcc 5.4.0 (posix thread model).

**Note that I have no trouble building and running release version_11 with the (almost) same configuration!**

gdb:
```
C:\Users\jie\Downloads\binaryen-master>gdb --args ./asm2wasm -h
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./asm2wasm...done.
(gdb) break wasm::SExpressionWasmBuilder::SExpressionWasmBuilder
Breakpoint 1 at 0x470936: file src/wasm-s-parser.h, line 272.
(gdb) run
Starting program: C:\Users\jie\Downloads\binaryen-master\asm2wasm.exe -h
[New Thread 4456.0x714]
[New Thread 4456.0xc20]
[New Thread 4456.0x5a8]
[New Thread 4456.0x380]

Breakpoint 1, wasm::SExpressionWasmBuilder::SExpressionWasmBuilder (
    this=0x263fc70, wasm=..., module=...) at src/wasm-s-parser.h:272
272       SExpressionWasmBuilder(Module& wasm, Element& module) : wasm(wasm), al
locator(wasm.allocator), importCounter(0), globalCounter(0) {
(gdb) print module[0]->str()
$1 = {str = 0x2653dc0 "module"}
(gdb) print MODULE
$2 = {<cashew::IString> = {str = 0x0}, <No data fields>}
(gdb) kill
Kill the program being debugged? (y or n) y
(gdb) quit
```

The batch script:
```
@echo off
cd C:\Users\jie\Downloads\binaryen-master

echo Set up env...
set cxx=g++
set flag=-std=c++11 -Isrc -O0 -g3 -D_GNU_SOURCE -msse2 -mfpmath=sse -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter
set compile=%cxx% %flag% -c
set build=%cxx% %flag%

rem goto skip
echo Compile asmjs...
%compile% src/asmjs/asm_v_wasm.cpp
%compile% src/asmjs/shared-constants.cpp
ar rcs libasmjs.a *.o
del *.o

echo Compile emscripten...
%compile% src/emscripten-optimizer/optimizer-shared.cpp
%compile% src/emscripten-optimizer/parser.cpp
%compile% src/emscripten-optimizer/simple_ast.cpp
ar rcs libemscripten.a *.o
del *.o

echo Compile passes...
%compile% src/passes/pass.cpp
%compile% src/passes/CoalesceLocals.cpp
%compile% src/passes/DeadCodeElimination.cpp
%compile% src/passes/DropReturnValues.cpp
%compile% src/passes/DuplicateFunctionElimination.cpp
%compile% src/passes/LowerIfElse.cpp
%compile% src/passes/MergeBlocks.cpp
%compile% src/passes/Metrics.cpp
%compile% src/passes/NameManager.cpp
%compile% src/passes/NameList.cpp
%compile% src/passes/OptimizeInstructions.cpp
%compile% src/passes/PostEmscripten.cpp
%compile% src/passes/Precompute.cpp
%compile% src/passes/Print.cpp
%compile% src/passes/RemoveImports.cpp
%compile% src/passes/RemoveMemory.cpp
%compile% src/passes/RemoveUnusedBrs.cpp
%compile% src/passes/RemoveUnusedNames.cpp
%compile% src/passes/RemoveUnusedFunctions.cpp
%compile% src/passes/ReorderLocals.cpp
%compile% src/passes/ReorderFunctions.cpp
%compile% src/passes/SimplifyLocals.cpp
%compile% src/passes/Vacuum.cpp
ar rcs libpasses.a *.o
del *.o

echo Compile support...
%compile% src/support/archive.cpp
%compile% src/support/bits.cpp
%compile% src/support/colors.cpp
%compile% src/support/command-line.cpp
%compile% src/support/file.cpp
%compile% src/support/safe_integer.cpp
%compile% src/support/threads.cpp
ar rcs libsupport.a *.o
del *.o

echo Building wasm-shell...
%build% -o wasm-shell src/tools/wasm-shell.cpp src/wasm.cpp -L. -lasmjs -lemscripten -lpasses -lsupport

echo Building wasm-opt...
%build% -o wasm-opt src/tools/wasm-opt.cpp src/wasm.cpp -L. -lasmjs -lemscripten -lpasses -lsupport

echo Building asm2wasm...
%build% -o asm2wasm src/tools/asm2wasm.cpp src/wasm.cpp -L. -lasmjs -lemscripten -lpasses -lsupport

echo Building s2wasm...
%build% -o s2wasm src/tools/s2wasm.cpp src/wasm-linker.cpp src/wasm.cpp -L. -lasmjs -lpasses -lsupport

echo Building wasm-as...
%build% -o wasm-as src/tools/wasm-as.cpp src/wasm.cpp -L. -lasmjs -lpasses -lsupport

echo Building wasm-dis...
%build% -o wasm-dis src/tools/wasm-dis.cpp src/wasm.cpp -L. -lpasses -lsupport -lasmjs

dir /b *.exe
```

**Comment by kripken** [comment]
asm2wasm doesn't use the `wasm-s-parser` stuff that is failing, so I suspect that is the OptimizeInstructions startup code which parses the list of optimizations. In a debug build the stack trace could show it more clearly.

It should basically be parsing `src/passes/OptimizeInstructions.wast.processed` which is included in the middle of `src/passes/OptimizeInstructions.cpp`. Is the first file of those modified locally perhaps? If not, maybe some line ending issue on windows?

**Comment by rongjiecomputer** [comment]
You are right, it is originated from `src/passes/OptimizeInstructions.cpp`.
```
(gdb) backtrace
#0  wasm::SExpressionWasmBuilder::SExpressionWasmBuilder (this=0x263fc70,
    wasm=..., module=...) at src/wasm-s-parser.h:272
#1  0x000000000045103b in wasm::PatternDatabase::PatternDatabase (
    this=0x5ac9c0 <wasm::database>) at src/passes/OptimizeInstructions.cpp:59
#2  0x000000000041f143 in __static_initialization_and_destruction_0 (
    __initialize_p=1, __priority=65535)
    at src/passes/OptimizeInstructions.cpp:74
#3  0x000000000041f16d in _GLOBAL__sub_I__ZN4wasm8I32_EXPRE ()
    at src/passes/OptimizeInstructions.cpp:179
#4  0x0000000000422755 in __do_global_ctors ()
#5  0x00000000004013bb in __tmainCRTStartup ()
#6  0x000000000040151b in mainCRTStartup ()
```
`src/passes/OptimizeInstructions.wast.processed` did have EOL issue when I opened it with Notepad, so I manually changed the EOL to `\n` and tried again. No luck.

Maybe I should copy-paste content of `src/passes/OptimizeInstructions.wast.processed` instead of using `#include "OptimizeInstructions.wast.processed"`? Since I used `-O0` flag, `static PatternDatabase database` is initialized even though it is not used, maybe `-O2` will work.

**Comment by rongjiecomputer** [comment]
I think I know what was the issue: the order of initialization of global variables.

I set a breakpoint at `__static_initialization_and_destruction_0` to check the initialization of global variables. But when I reached `wasm::PatternDatabase::PatternDatabase` from `OptimizeInstructions.cpp`, `Name MODULE("module")` from `wasm.cpp` was not initialized yet. This is why `assert(module[0]->str() == MODULE)` in `wasm::SExpressionWasmBuilder::SExpressionWasmBuilder` failed.

```
(gdb) print module[0]->str()
$1 = {str = 0x2653dc0 "module"}
(gdb) print MODULE
$2 = {<cashew::IString> = {str = 0x0}, <No data fields>}
```

Do you know how to manually re-order the sequence of global variables initialization?

**Comment by rongjiecomputer** [comment]
I found a workaround for this: instead of declaring `static PatternDatabase database` in global scope of `OptimizeInstructions.cpp`, declare it in `OptimizeInstructions::visitExpression` since `database` is only used in this function. It works for now, but not if in the future `database` is used by more than one function across multiple codes.

**Comment by kripken** [comment]
Good find! Yes, I think that's the bug here.

The fix is indeed to create it not during startup. Probably in the global scope it could be a pointer set to null, and initialized if not already initialized, in the constructor of `OptimizeInstructions`. There might need to be thread-safety, though, as multiple such objects can be created (although I believe we currently create them all on the main thread).

**Comment by kripken** [comment]
This should now be fixed. Thanks again for reporting this and finding the problem.

**Comment by rongjiecomputer** [comment]
#694 The fix is working nicely, should be no problem now!
