### ISSUE TITLE
check.py runtime error after building for split.wast check

### ISSUE THREAD

**Issue by vyom1611** [WebAssembly/binaryen#6944]
I just built the project using ninja, and then when I run check.py script, I keep getting this error:

```
./check.py
[ checking --version ... ]

Parsed CHANGELOG.md version: 119

.. /Users/vyomsharma/binaryen/bin/wasm-as --version
.. /Users/vyomsharma/binaryen/bin/wasm-ctor-eval --version
.. /Users/vyomsharma/binaryen/bin/wasm-dis --version
.. /Users/vyomsharma/binaryen/bin/wasm-emscripten-finalize --version
.. /Users/vyomsharma/binaryen/bin/wasm-fuzz-lattices --version
.. /Users/vyomsharma/binaryen/bin/wasm-fuzz-types --version
.. /Users/vyomsharma/binaryen/bin/wasm-merge --version
.. /Users/vyomsharma/binaryen/bin/wasm-metadce --version
.. /Users/vyomsharma/binaryen/bin/wasm-opt --version
.. /Users/vyomsharma/binaryen/bin/wasm-reduce --version
.. /Users/vyomsharma/binaryen/bin/wasm-shell --version
.. /Users/vyomsharma/binaryen/bin/wasm-split --version
.. /Users/vyomsharma/binaryen/bin/wasm2js --version

[ checking wasm-opt -o notation... ]

executing:  /Users/vyomsharma/binaryen/bin/wasm-opt /Users/vyomsharma/binaryen/test/hello_world.wat -o a.wat -S -q
executing:  /Users/vyomsharma/binaryen/bin/wasm-opt /Users/vyomsharma/binaryen/test/hello_world.wat -o a.wat -S -q --no-validation

[ checking wasm-opt binary reading/writing... ]

executing:  /Users/vyomsharma/binaryen/bin/wasm-opt a.wat -o a.wasm -q
executing:  /Users/vyomsharma/binaryen/bin/wasm-opt a.wasm -o b.wast -S -q

[ checking wasm-opt passes... ]

.. O.wasm
executing:  /Users/vyomsharma/binaryen/bin/wasm-opt -O split.wast -q --print
Traceback (most recent call last):
  File "/Users/vyomsharma/binaryen/./check.py", line 408, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/vyomsharma/binaryen/./check.py", line 391, in main
    TEST_SUITES[test]()
  File "/Users/vyomsharma/binaryen/scripts/test/wasm_opt.py", line 69, in test_wasm_opt
    curr = support.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vyomsharma/binaryen/scripts/test/support.py", line 193, in run_command
    raise Exception(('run_command failed (%s)' % code, out + str(err or '')))
Exception: ('run_command failed (-10)', '')
```

Things I noticed:
1. I cannot find split.wast in the test folder
2. using find --name, I found out that it is in a //out folder which I cannot see, and split.wast 's contents are not readable in my ide editor.

**Comment by kripken** [comment]
`split.wast` should be in `out/test/split.wast`. Maybe there is a permissions issue with that folder?

Does `/Users/vyomsharma/binaryen/bin/wasm-opt -O out/test/split.wast -q --print` work? (that adds the full path)

Which OS is this on?

**Comment by vyom1611** [comment]
doing `bin/wasm-opt -O out/test/split.wast -q --print` gives me
```
zsh: bus error  bin/wasm-opt -O out/test/split.wast -q --print
```

Running this ons MacOS (M2)

**Comment by kripken** [comment]
Hmm, sorry, I'm not sure what "bus error" is on MacOS, but I think that is the problem.

**Comment by vyom1611** [comment]
After updating to MacOS Sequoia, the problem resolved itself somehow.
