### ISSUE TITLE
check.py fails to run 'lit' test suite

### ISSUE THREAD

**Issue by osa1** [WebAssembly/binaryen#6961]
`check.py` reports these test suites:

```
$ ./check.py --list-suites
version
wasm-opt
wasm-dis
crash
dylink
ctor-eval
wasm-metadce
wasm-reduce
spec
lld
wasm2js
validator
example
unit
binaryenjs
binaryenjs_wasm
lit
gtest
```

Many of them I can run, for example `check.py gtest`, `check.py unit`, `check.py spec` work.

But `lit` fails:

```
$ ./check.py lit
Traceback (most recent call last):
  File "/usr/local/google/home/omersa/binaryen/bin/binaryen-lit", line 18, in <module>
    from lit.main import main
ModuleNotFoundError: No module named 'lit'
Traceback (most recent call last):
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 408, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 391, in main
    TEST_SUITES[test]()
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 332, in run_lit
    shared.with_pass_debug(run)
  File "/usr/local/google/home/omersa/binaryen/scripts/test/shared.py", line 551, in with_pass_debug
    check()
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 330, in run
    raise Exception("lit test failed")
Exception: lit test failed
```

How do I run the 'lit' test suite?

**Comment by kripken** [comment]
I think `lit` needs to be installed, see

https://github.com/WebAssembly/binaryen?tab=readme-ov-file#setting-up-dependencies

**Comment by osa1** [comment]
Thanks!.

**Comment by osa1** [comment]
Sorry for reviving this old thread, but I don't think the instructions in the README install `lit`.

```
$ ./third_party/setup.py all
Setting up mozjs ...
* Platform: linux-x86_64
* Latest version: 140.0b8
* Downloading to: /usr/local/google/home/omersa/binaryen/third_party/mozjs
* Complete
Setting up V8 ...
* Platform: linux64
* Latest version: 13.9.143
* Downloading to: /usr/local/google/home/omersa/binaryen/third_party/v8
* Complete
Setting up WABT ...
* Platform: ubuntu
* Latest release: https://github.com/WebAssembly/wabt/releases/download/1.0.37/wabt-1.0.37-ubuntu-20.04.tar.gz
* Downloading to: /usr/local/google/home/omersa/binaryen/third_party/wabt/bin
* Complete

$ cmake . -DCMAKE_BUILD_TYPE=Debug && make -j10
...

$ ./check.py --binaryen-bin=bin lit
warning: no node found (did not check proper js form)
Traceback (most recent call last):
  File "/usr/local/google/home/omersa/binaryen/bin/binaryen-lit", line 18, in <module>
    from lit.main import main
ModuleNotFoundError: No module named 'lit'
Traceback (most recent call last):
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 407, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 390, in main
    TEST_SUITES[test]()
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 331, in run_lit
    shared.with_pass_debug(run)
  File "/usr/local/google/home/omersa/binaryen/scripts/test/shared.py", line 647, in with_pass_debug
    check()
  File "/usr/local/google/home/omersa/binaryen/./check.py", line 329, in run
    raise Exception("lit test failed")
Exception: lit test failed
```

Looking at `setup.py` source code, I don't think it install LLVM tools.

Should we ask users to manually install LLVM tools? Should we update `setup.py` to install `lit`?

**Comment by osa1** [comment]
Nvm, I don't know how to read. It's this line:

```
pip3 install -r requirements-dev.txt
```
