### ISSUE TITLE
binaryen 120: "orphan test output" errors when running wasm2js tests

### ISSUE THREAD

**Issue by rathann** [WebAssembly/binaryen#7045]
I'm getting the following Tracebacks when running the testsuite for 120:

```
$ ./check.py --binaryen-bin /builddir/build/BUILD/binaryen-120-build/BUILDROOT/usr/bin --binaryen-lib /builddir/build/BUILD/binaryen-120-build/BUILDROOT/usr/lib64/binaryen
...
orphan test output: traps.2asm.js
Traceback (most recent call last):
  File "/builddir/build/BUILD/binaryen-120-build/binaryen-version_120/./check.py", line 408, in <module>
    sys.exit(main())
             ~~~~^^
  File "/builddir/build/BUILD/binaryen-120-build/binaryen-version_120/./check.py", line 391, in main
    TEST_SUITES[test]()
    ~~~~~~~~~~~~~~~~~^^
  File "/builddir/build/BUILD/binaryen-120-build/binaryen-version_120/scripts/test/wasm2js.py", line 152, in test_wasm2js
    check_for_stale_files()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/builddir/build/BUILD/binaryen-120-build/binaryen-version_120/scripts/test/wasm2js.py", line 54, in check_for_stale_files
    shared.fail_with_error('orphan test output: %s' % f)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/binaryen-120-build/binaryen-version_120/scripts/test/shared.py", line 335, in fail_with_error
    raise Exception(msg)
Exception: orphan test output: traps.2asm.js

```

This occurs for each of the following files in test/wasm2js:

```
br.2asm.js
break-drop.2asm.js
br_table.2asm.js
comments.2asm.js
empty_imported_table.2asm.js
empty_table.2asm.js
endianness.2asm.js
f32.2asm.js
f32_cmp.2asm.js
f64_cmp.2asm.js
fac.2asm.js
float_misc.2asm.js
forward.2asm.js
func_ptrs.2asm.js
get_local.2asm.js
grow_memory.2asm.js
i32.2asm.js
int_exprs.2asm.js
labels.2asm.js
left-to-right.2asm.js
set_local.2asm.js
switch.2asm.js
tee_local.2asm.js
traps.2asm.js
```

**Comment by rathann** [comment]
> I think that means it can't find the sources for those tests. Perhaps you need to fetch the spec test submodule?
> 
> ```
> git submodule init
> git submodule update
> ```

Ah. I was using the GitHub-generated tarballs. Looks like I need to make a separate tarball of the spec tests, then.

**Comment by rathann** [comment]
After unpacking WebAssembly/testsuite tarball in the right place, the tests succeed. No bug here.
